/ietf-interfaces/interfaces/interface|name:tilld0|/enabled true
/ietf-interfaces/interfaces/interface|name:tilld1|/enabled true
/ietf-interfaces/interfaces/interface|name:tilld2|/enabled true
/ietf-interfaces/interfaces/interface|name:tilld3|/enabled true
