// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/argmax_matcher.proto

#include "object_detection/protos/argmax_matcher.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace object_detection {
namespace protos {
PROTOBUF_CONSTEXPR ArgMaxMatcher::ArgMaxMatcher(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.ignore_thresholds_)*/false
  , /*decltype(_impl_.force_match_for_each_row_)*/false
  , /*decltype(_impl_.use_matmul_gather_)*/false
  , /*decltype(_impl_.negatives_lower_than_unmatched_)*/true
  , /*decltype(_impl_.matched_threshold_)*/0.5f
  , /*decltype(_impl_.unmatched_threshold_)*/0.5f} {}
struct ArgMaxMatcherDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ArgMaxMatcherDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ArgMaxMatcherDefaultTypeInternal() {}
  union {
    ArgMaxMatcher _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ArgMaxMatcherDefaultTypeInternal _ArgMaxMatcher_default_instance_;
}  // namespace protos
}  // namespace object_detection
static ::_pb::Metadata file_level_metadata_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto = nullptr;

const uint32_t TableStruct_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::ArgMaxMatcher, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::ArgMaxMatcher, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::ArgMaxMatcher, _impl_.matched_threshold_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::ArgMaxMatcher, _impl_.unmatched_threshold_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::ArgMaxMatcher, _impl_.ignore_thresholds_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::ArgMaxMatcher, _impl_.negatives_lower_than_unmatched_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::ArgMaxMatcher, _impl_.force_match_for_each_row_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::ArgMaxMatcher, _impl_.use_matmul_gather_),
  4,
  5,
  0,
  3,
  1,
  2,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 12, -1, sizeof(::object_detection::protos::ArgMaxMatcher)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::object_detection::protos::_ArgMaxMatcher_default_instance_._instance,
};

const char descriptor_table_protodef_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n,object_detection/protos/argmax_matcher"
  ".proto\022\027object_detection.protos\"\354\001\n\rArgM"
  "axMatcher\022\036\n\021matched_threshold\030\001 \001(\002:\0030."
  "5\022 \n\023unmatched_threshold\030\002 \001(\002:\0030.5\022 \n\021i"
  "gnore_thresholds\030\003 \001(\010:\005false\022,\n\036negativ"
  "es_lower_than_unmatched\030\004 \001(\010:\004true\022\'\n\030f"
  "orce_match_for_each_row\030\005 \001(\010:\005false\022 \n\021"
  "use_matmul_gather\030\006 \001(\010:\005false"
  ;
static ::_pbi::once_flag descriptor_table_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto = {
    false, false, 310, descriptor_table_protodef_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto,
    "object_detection/protos/argmax_matcher.proto",
    &descriptor_table_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto::offsets,
    file_level_metadata_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto, file_level_enum_descriptors_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto,
    file_level_service_descriptors_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto_getter() {
  return &descriptor_table_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto(&descriptor_table_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto);
namespace object_detection {
namespace protos {

// ===================================================================

class ArgMaxMatcher::_Internal {
 public:
  using HasBits = decltype(std::declval<ArgMaxMatcher>()._impl_._has_bits_);
  static void set_has_matched_threshold(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_unmatched_threshold(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_ignore_thresholds(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_negatives_lower_than_unmatched(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_force_match_for_each_row(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_use_matmul_gather(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

ArgMaxMatcher::ArgMaxMatcher(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:object_detection.protos.ArgMaxMatcher)
}
ArgMaxMatcher::ArgMaxMatcher(const ArgMaxMatcher& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ArgMaxMatcher* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.ignore_thresholds_){}
    , decltype(_impl_.force_match_for_each_row_){}
    , decltype(_impl_.use_matmul_gather_){}
    , decltype(_impl_.negatives_lower_than_unmatched_){}
    , decltype(_impl_.matched_threshold_){}
    , decltype(_impl_.unmatched_threshold_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.ignore_thresholds_, &from._impl_.ignore_thresholds_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.unmatched_threshold_) -
    reinterpret_cast<char*>(&_impl_.ignore_thresholds_)) + sizeof(_impl_.unmatched_threshold_));
  // @@protoc_insertion_point(copy_constructor:object_detection.protos.ArgMaxMatcher)
}

inline void ArgMaxMatcher::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.ignore_thresholds_){false}
    , decltype(_impl_.force_match_for_each_row_){false}
    , decltype(_impl_.use_matmul_gather_){false}
    , decltype(_impl_.negatives_lower_than_unmatched_){true}
    , decltype(_impl_.matched_threshold_){0.5f}
    , decltype(_impl_.unmatched_threshold_){0.5f}
  };
}

ArgMaxMatcher::~ArgMaxMatcher() {
  // @@protoc_insertion_point(destructor:object_detection.protos.ArgMaxMatcher)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ArgMaxMatcher::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ArgMaxMatcher::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ArgMaxMatcher::Clear() {
// @@protoc_insertion_point(message_clear_start:object_detection.protos.ArgMaxMatcher)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.ignore_thresholds_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.use_matmul_gather_) -
      reinterpret_cast<char*>(&_impl_.ignore_thresholds_)) + sizeof(_impl_.use_matmul_gather_));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000038u) {
    _impl_.negatives_lower_than_unmatched_ = true;
    _impl_.matched_threshold_ = 0.5f;
    _impl_.unmatched_threshold_ = 0.5f;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ArgMaxMatcher::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional float matched_threshold = 1 [default = 0.5];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _Internal::set_has_matched_threshold(&has_bits);
          _impl_.matched_threshold_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // optional float unmatched_threshold = 2 [default = 0.5];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _Internal::set_has_unmatched_threshold(&has_bits);
          _impl_.unmatched_threshold_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // optional bool ignore_thresholds = 3 [default = false];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_ignore_thresholds(&has_bits);
          _impl_.ignore_thresholds_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool negatives_lower_than_unmatched = 4 [default = true];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_negatives_lower_than_unmatched(&has_bits);
          _impl_.negatives_lower_than_unmatched_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool force_match_for_each_row = 5 [default = false];
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _Internal::set_has_force_match_for_each_row(&has_bits);
          _impl_.force_match_for_each_row_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool use_matmul_gather = 6 [default = false];
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _Internal::set_has_use_matmul_gather(&has_bits);
          _impl_.use_matmul_gather_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ArgMaxMatcher::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:object_detection.protos.ArgMaxMatcher)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional float matched_threshold = 1 [default = 0.5];
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_matched_threshold(), target);
  }

  // optional float unmatched_threshold = 2 [default = 0.5];
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_unmatched_threshold(), target);
  }

  // optional bool ignore_thresholds = 3 [default = false];
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_ignore_thresholds(), target);
  }

  // optional bool negatives_lower_than_unmatched = 4 [default = true];
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_negatives_lower_than_unmatched(), target);
  }

  // optional bool force_match_for_each_row = 5 [default = false];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_force_match_for_each_row(), target);
  }

  // optional bool use_matmul_gather = 6 [default = false];
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(6, this->_internal_use_matmul_gather(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:object_detection.protos.ArgMaxMatcher)
  return target;
}

size_t ArgMaxMatcher::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:object_detection.protos.ArgMaxMatcher)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional bool ignore_thresholds = 3 [default = false];
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 1;
    }

    // optional bool force_match_for_each_row = 5 [default = false];
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

    // optional bool use_matmul_gather = 6 [default = false];
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 1;
    }

    // optional bool negatives_lower_than_unmatched = 4 [default = true];
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 1;
    }

    // optional float matched_threshold = 1 [default = 0.5];
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 4;
    }

    // optional float unmatched_threshold = 2 [default = 0.5];
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 4;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ArgMaxMatcher::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ArgMaxMatcher::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ArgMaxMatcher::GetClassData() const { return &_class_data_; }


void ArgMaxMatcher::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ArgMaxMatcher*>(&to_msg);
  auto& from = static_cast<const ArgMaxMatcher&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:object_detection.protos.ArgMaxMatcher)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.ignore_thresholds_ = from._impl_.ignore_thresholds_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.force_match_for_each_row_ = from._impl_.force_match_for_each_row_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.use_matmul_gather_ = from._impl_.use_matmul_gather_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.negatives_lower_than_unmatched_ = from._impl_.negatives_lower_than_unmatched_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.matched_threshold_ = from._impl_.matched_threshold_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.unmatched_threshold_ = from._impl_.unmatched_threshold_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ArgMaxMatcher::CopyFrom(const ArgMaxMatcher& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:object_detection.protos.ArgMaxMatcher)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArgMaxMatcher::IsInitialized() const {
  return true;
}

void ArgMaxMatcher::InternalSwap(ArgMaxMatcher* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ArgMaxMatcher, _impl_.use_matmul_gather_)
      + sizeof(ArgMaxMatcher::_impl_.use_matmul_gather_)
      - PROTOBUF_FIELD_OFFSET(ArgMaxMatcher, _impl_.ignore_thresholds_)>(
          reinterpret_cast<char*>(&_impl_.ignore_thresholds_),
          reinterpret_cast<char*>(&other->_impl_.ignore_thresholds_));
  swap(_impl_.negatives_lower_than_unmatched_, other->_impl_.negatives_lower_than_unmatched_);
  swap(_impl_.matched_threshold_, other->_impl_.matched_threshold_);
  swap(_impl_.unmatched_threshold_, other->_impl_.unmatched_threshold_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ArgMaxMatcher::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto_getter, &descriptor_table_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto_once,
      file_level_metadata_object_5fdetection_2fprotos_2fargmax_5fmatcher_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace object_detection
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::object_detection::protos::ArgMaxMatcher*
Arena::CreateMaybeMessage< ::object_detection::protos::ArgMaxMatcher >(Arena* arena) {
  return Arena::CreateMessageInternal< ::object_detection::protos::ArgMaxMatcher >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
