// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/grid_anchor_generator.proto

#include "object_detection/protos/grid_anchor_generator.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace object_detection {
namespace protos {
PROTOBUF_CONSTEXPR GridAnchorGenerator::GridAnchorGenerator(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.scales_)*/{}
  , /*decltype(_impl_.aspect_ratios_)*/{}
  , /*decltype(_impl_.height_offset_)*/0
  , /*decltype(_impl_.width_offset_)*/0
  , /*decltype(_impl_.height_)*/256
  , /*decltype(_impl_.width_)*/256
  , /*decltype(_impl_.height_stride_)*/16
  , /*decltype(_impl_.width_stride_)*/16} {}
struct GridAnchorGeneratorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GridAnchorGeneratorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GridAnchorGeneratorDefaultTypeInternal() {}
  union {
    GridAnchorGenerator _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GridAnchorGeneratorDefaultTypeInternal _GridAnchorGenerator_default_instance_;
}  // namespace protos
}  // namespace object_detection
static ::_pb::Metadata file_level_metadata_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto = nullptr;

const uint32_t TableStruct_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::GridAnchorGenerator, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::GridAnchorGenerator, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::GridAnchorGenerator, _impl_.height_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::GridAnchorGenerator, _impl_.width_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::GridAnchorGenerator, _impl_.height_stride_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::GridAnchorGenerator, _impl_.width_stride_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::GridAnchorGenerator, _impl_.height_offset_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::GridAnchorGenerator, _impl_.width_offset_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::GridAnchorGenerator, _impl_.scales_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::GridAnchorGenerator, _impl_.aspect_ratios_),
  2,
  3,
  4,
  5,
  0,
  1,
  ~0u,
  ~0u,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 14, -1, sizeof(::object_detection::protos::GridAnchorGenerator)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::object_detection::protos::_GridAnchorGenerator_default_instance_._instance,
};

const char descriptor_table_protodef_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n3object_detection/protos/grid_anchor_ge"
  "nerator.proto\022\027object_detection.protos\"\315"
  "\001\n\023GridAnchorGenerator\022\023\n\006height\030\001 \001(\005:\003"
  "256\022\022\n\005width\030\002 \001(\005:\003256\022\031\n\rheight_stride"
  "\030\003 \001(\005:\00216\022\030\n\014width_stride\030\004 \001(\005:\00216\022\030\n\r"
  "height_offset\030\005 \001(\005:\0010\022\027\n\014width_offset\030\006"
  " \001(\005:\0010\022\016\n\006scales\030\007 \003(\002\022\025\n\raspect_ratios"
  "\030\010 \003(\002"
  ;
static ::_pbi::once_flag descriptor_table_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto = {
    false, false, 286, descriptor_table_protodef_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto,
    "object_detection/protos/grid_anchor_generator.proto",
    &descriptor_table_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto::offsets,
    file_level_metadata_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto, file_level_enum_descriptors_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto,
    file_level_service_descriptors_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto_getter() {
  return &descriptor_table_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto(&descriptor_table_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto);
namespace object_detection {
namespace protos {

// ===================================================================

class GridAnchorGenerator::_Internal {
 public:
  using HasBits = decltype(std::declval<GridAnchorGenerator>()._impl_._has_bits_);
  static void set_has_height(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_width(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_height_stride(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_width_stride(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_height_offset(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_width_offset(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

GridAnchorGenerator::GridAnchorGenerator(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:object_detection.protos.GridAnchorGenerator)
}
GridAnchorGenerator::GridAnchorGenerator(const GridAnchorGenerator& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GridAnchorGenerator* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.scales_){from._impl_.scales_}
    , decltype(_impl_.aspect_ratios_){from._impl_.aspect_ratios_}
    , decltype(_impl_.height_offset_){}
    , decltype(_impl_.width_offset_){}
    , decltype(_impl_.height_){}
    , decltype(_impl_.width_){}
    , decltype(_impl_.height_stride_){}
    , decltype(_impl_.width_stride_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.height_offset_, &from._impl_.height_offset_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.width_stride_) -
    reinterpret_cast<char*>(&_impl_.height_offset_)) + sizeof(_impl_.width_stride_));
  // @@protoc_insertion_point(copy_constructor:object_detection.protos.GridAnchorGenerator)
}

inline void GridAnchorGenerator::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.scales_){arena}
    , decltype(_impl_.aspect_ratios_){arena}
    , decltype(_impl_.height_offset_){0}
    , decltype(_impl_.width_offset_){0}
    , decltype(_impl_.height_){256}
    , decltype(_impl_.width_){256}
    , decltype(_impl_.height_stride_){16}
    , decltype(_impl_.width_stride_){16}
  };
}

GridAnchorGenerator::~GridAnchorGenerator() {
  // @@protoc_insertion_point(destructor:object_detection.protos.GridAnchorGenerator)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GridAnchorGenerator::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.scales_.~RepeatedField();
  _impl_.aspect_ratios_.~RepeatedField();
}

void GridAnchorGenerator::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GridAnchorGenerator::Clear() {
// @@protoc_insertion_point(message_clear_start:object_detection.protos.GridAnchorGenerator)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.scales_.Clear();
  _impl_.aspect_ratios_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    ::memset(&_impl_.height_offset_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.width_offset_) -
        reinterpret_cast<char*>(&_impl_.height_offset_)) + sizeof(_impl_.width_offset_));
    _impl_.height_ = 256;
    _impl_.width_ = 256;
    _impl_.height_stride_ = 16;
    _impl_.width_stride_ = 16;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GridAnchorGenerator::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 height = 1 [default = 256];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_height(&has_bits);
          _impl_.height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 width = 2 [default = 256];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_width(&has_bits);
          _impl_.width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 height_stride = 3 [default = 16];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_height_stride(&has_bits);
          _impl_.height_stride_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 width_stride = 4 [default = 16];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_width_stride(&has_bits);
          _impl_.width_stride_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 height_offset = 5 [default = 0];
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _Internal::set_has_height_offset(&has_bits);
          _impl_.height_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 width_offset = 6 [default = 0];
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _Internal::set_has_width_offset(&has_bits);
          _impl_.width_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated float scales = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 61)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_scales(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
            ptr += sizeof(float);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<61>(ptr));
        } else if (static_cast<uint8_t>(tag) == 58) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_scales(), ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated float aspect_ratios = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 69)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_aspect_ratios(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
            ptr += sizeof(float);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<69>(ptr));
        } else if (static_cast<uint8_t>(tag) == 66) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_aspect_ratios(), ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GridAnchorGenerator::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:object_detection.protos.GridAnchorGenerator)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 height = 1 [default = 256];
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_height(), target);
  }

  // optional int32 width = 2 [default = 256];
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_width(), target);
  }

  // optional int32 height_stride = 3 [default = 16];
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_height_stride(), target);
  }

  // optional int32 width_stride = 4 [default = 16];
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_width_stride(), target);
  }

  // optional int32 height_offset = 5 [default = 0];
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_height_offset(), target);
  }

  // optional int32 width_offset = 6 [default = 0];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_width_offset(), target);
  }

  // repeated float scales = 7;
  for (int i = 0, n = this->_internal_scales_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(7, this->_internal_scales(i), target);
  }

  // repeated float aspect_ratios = 8;
  for (int i = 0, n = this->_internal_aspect_ratios_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(8, this->_internal_aspect_ratios(i), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:object_detection.protos.GridAnchorGenerator)
  return target;
}

size_t GridAnchorGenerator::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:object_detection.protos.GridAnchorGenerator)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float scales = 7;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_scales_size());
    size_t data_size = 4UL * count;
    total_size += 1 *
                  ::_pbi::FromIntSize(this->_internal_scales_size());
    total_size += data_size;
  }

  // repeated float aspect_ratios = 8;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_aspect_ratios_size());
    size_t data_size = 4UL * count;
    total_size += 1 *
                  ::_pbi::FromIntSize(this->_internal_aspect_ratios_size());
    total_size += data_size;
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional int32 height_offset = 5 [default = 0];
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_height_offset());
    }

    // optional int32 width_offset = 6 [default = 0];
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_width_offset());
    }

    // optional int32 height = 1 [default = 256];
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_height());
    }

    // optional int32 width = 2 [default = 256];
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_width());
    }

    // optional int32 height_stride = 3 [default = 16];
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_height_stride());
    }

    // optional int32 width_stride = 4 [default = 16];
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_width_stride());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GridAnchorGenerator::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GridAnchorGenerator::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GridAnchorGenerator::GetClassData() const { return &_class_data_; }


void GridAnchorGenerator::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GridAnchorGenerator*>(&to_msg);
  auto& from = static_cast<const GridAnchorGenerator&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:object_detection.protos.GridAnchorGenerator)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.scales_.MergeFrom(from._impl_.scales_);
  _this->_impl_.aspect_ratios_.MergeFrom(from._impl_.aspect_ratios_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.height_offset_ = from._impl_.height_offset_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.width_offset_ = from._impl_.width_offset_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.height_ = from._impl_.height_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.width_ = from._impl_.width_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.height_stride_ = from._impl_.height_stride_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.width_stride_ = from._impl_.width_stride_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GridAnchorGenerator::CopyFrom(const GridAnchorGenerator& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:object_detection.protos.GridAnchorGenerator)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GridAnchorGenerator::IsInitialized() const {
  return true;
}

void GridAnchorGenerator::InternalSwap(GridAnchorGenerator* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.scales_.InternalSwap(&other->_impl_.scales_);
  _impl_.aspect_ratios_.InternalSwap(&other->_impl_.aspect_ratios_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GridAnchorGenerator, _impl_.width_offset_)
      + sizeof(GridAnchorGenerator::_impl_.width_offset_)
      - PROTOBUF_FIELD_OFFSET(GridAnchorGenerator, _impl_.height_offset_)>(
          reinterpret_cast<char*>(&_impl_.height_offset_),
          reinterpret_cast<char*>(&other->_impl_.height_offset_));
  swap(_impl_.height_, other->_impl_.height_);
  swap(_impl_.width_, other->_impl_.width_);
  swap(_impl_.height_stride_, other->_impl_.height_stride_);
  swap(_impl_.width_stride_, other->_impl_.width_stride_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GridAnchorGenerator::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto_getter, &descriptor_table_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto_once,
      file_level_metadata_object_5fdetection_2fprotos_2fgrid_5fanchor_5fgenerator_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace object_detection
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::object_detection::protos::GridAnchorGenerator*
Arena::CreateMaybeMessage< ::object_detection::protos::GridAnchorGenerator >(Arena* arena) {
  return Arena::CreateMessageInternal< ::object_detection::protos::GridAnchorGenerator >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
