/*
*
* Copyright (c) {2015 - 2025} Texas Instruments Incorporated
*
* All rights reserved not granted herein.
*
* Limited License.
*
* Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
* license under copyrights and patents it now or hereafter owns or controls to make,
* have made, use, import, offer to sell and sell ("Utilize") this software subject to the
* terms herein.  With respect to the foregoing patent license, such license is granted
* solely to the extent that any such patent is necessary to Utilize the software alone.
* The patent license shall not apply to any combinations which include this software,
* other than combinations with devices manufactured by or for TI ("TI Devices").
* No hardware patent is licensed hereunder.
*
* Redistributions must preserve existing copyright notices and reproduce this license
* (including the above copyright notice and the disclaimer and (if applicable) source
* code license limitations below) in the documentation and/or other materials provided
* with the distribution
*
* Redistribution and use in binary form, without modification, are permitted provided
* that the following conditions are met:
*
* *       No reverse engineering, decompilation, or disassembly of this software is
* permitted with respect to any software provided in binary form.
*
* *       any redistribution and use are licensed by TI for use only with TI Devices.
*
* *       Nothing shall obligate TI to provide you with source code for the software
* licensed and provided to you in object code.
*
* If software source code is provided to you, modification and redistribution of the
* source code are permitted provided that the following conditions are met:
*
* *       any redistribution and use of the source code, including any resulting derivative
* works, are licensed by TI for use only with TI Devices.
*
* *       any redistribution and use of any object code compiled from the source code
* and any resulting derivative works, are licensed by TI for use only with TI Devices.
*
* Neither the name of Texas Instruments Incorporated nor the names of its suppliers
*
* may be used to endorse or promote products derived from this software without
* specific prior written permission.
*
* DISCLAIMER.
*
* THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS
* OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
* BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/


/**
@file      tidl_forceNegativeTest.h
brief      This file defines kernel-specific ENUM flags to verify whether the safety flag is set. \n
           This interface ensuring kernel pointer parameters are set to NULL for safety fail checks.

@version 0.1 Jan 2025 : Initial Code
*/
#ifndef TIDL_FORCENEGATIVETEST_H
#define TIDL_FORCENEGATIVETEST_H

#define TIDL_SAFETY_FLAG_ALLOC_FORCE_NETVERSION (1)
#define TIDL_SAFETY_FLAG_ALLOC_FORCE_VPRINTF_NULL (2)
#define TIDL_SAFETY_FLAG_ALLOC_FORCE_NET_NULL (3)


#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_ALIGNMENT_ZERO (10)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_NUMLAYERS_MAX (11)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_WLSUPERGRP_NULL (12)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_WLUNIT_NULL (1200)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_OUTPTRS_NULL (1201)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_OUTPRTS_INVALID_DATATYPE (1202)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_INPTRS_INDATAPARAMS_NULL (1203)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_INPTRS_GC_TRACE_SCRATCHSIZE_INVALID (1204)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_INPTRS_NC_TRACE_SCRATCHSIZE_INVALID (1205)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_OUTDATABUF_NUMLAYERS_MAX (1206)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_MOVENET_ALGLAYERPARAMS_NULL (1208)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_NUMLAYERS_MIN (1209)

#define TIDL_SAFETY_FLAG_GC_HELPER_FORCE_WL_UNIT_NULL (1300)


#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_WL_NULL (50)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_OUTPRT_NULL (51)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_COMMONPROCESS_WL_NULL (52)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_WLLOOPITR_NULL (53)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_SHIFT_NULL (54)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_DMAUTILSCONTEXT_NULL (55)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_PAD_DMAUTILSCONTEXT_NULL (56)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_SCRATCHDATASIZE_NEG (57)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_OUITPUT_SIZE_NEG (58)

#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_SCRATCHDATASIZE_ALLOC (57)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_OUITPUT_SIZE_ALLOC (58)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_SCRATCHDATASIZE_INIT (59)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_OUITPUT_SIZE_INIT (60)

#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_GRPID_INVALID (1210)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_GRPIDX_INVALID (1211)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_LNKTYPE_INVALID (1212)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_PITCHWIDTH_INVALID (1213)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_FLOWCNT_INVALID (1214)
#define TIDL_SAFETY_FLAG_ALGUTILS_GETPAD_FORCE_PADPARAMS_NULL (1215)
#define TIDL_SAFETY_FLAG_DEVICE_UTILS_FORCE_PADPARAM_PAD_TYPE (1216)

#define TIDL_SAFETY_FLAG_ALG_ALLOC_FORCE_GCHELPERHNDLE_NULL (13)
#define TIDL_SAFETY_FLAG_ALG_ALLOC_FORCE_LOOP_FLAG_CHECK (14)
#define TIDL_SAFETY_FLAG_ALG_ALLOC_FORCE_ALGLAYERSSIZE (15)
#define TIDL_SAFETY_FLAG_ALG_ALLOC_FORCE_SCRATCHBUFFSIZE (16)
#define TIDL_SAFETY_FLAG_ALG_ALLOC_FORCE_REFSCRATCHBUFFSIZE (17)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_L3BASEPTR_NULL (18)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_INTALGHNDLE_NULL (19)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_L2BASEPTR_NULL (20)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_PRVCNTX_NULL (21)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_WTMEMBASEPTR_NULL (22)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_DMAUTILSCNTX_NULL (23)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_ZEROVEC1K_NULL (24)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_MCPYTR_NULL (25)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_PREMPHNDLE_NULL (26)
#define TIDL_SAFETY_FLAG_ALG_UTILS_FORCE_PREMPHNDLEDDR_NULL (27)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_WHILEFLAG_ZERO (28)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_WLUNIT_NULL (29)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_LYERSPRMMEMTBOFS_MAX (30)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_PRMMEMTBOFS_MAX (31)
#define TIDL_SAFETY_FLAG_ALG_FREE_FORCE_LSTHNDLE_INVALID (32)
#define TIDL_SAFETY_FLAG_ALG_DEACT_FORCE_ALGSTATE_INAVALID (33)
#define TIDL_SAFETY_FLAG_ALG_DEACT_FORCE_INTALGHNDLE_NULL (34)
#define TIDL_SAFETY_FLAG_ALG_ACT_FORCE_ALGSTATE_INVALID (35)
#define TIDL_SAFETY_FLAG_ALG_ACT_FORCE_INITDMAUTILSTATE_INVALID (36)
#define TIDL_SAFETY_FLAG_ALG_ACT_FORCE_2DMEMCPYSTATE_INVALID (37)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_TRACEWRITE_INVALID (38)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_NUMLAYERS_ZERO (39)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_WHILEFLAG_ZERO (40)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_GETLYRSTATE_INVALID (41)
#define TIDL_SAFETY_FLAG_ALG_2DMEMCPY_FORCE_INTALGHNDLE_NULL (42)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_LNKPTR_NULL (43)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_GETEXECNUMLYR_NULL (44)
#define TIDL_SAFETY_FLAG_TIDLRT_UTILS_FORCE_DMACREATE_NULL (45)
#define TIDL_SAFETY_FLAG_TIDLRT_ALLOC_FORCE_TRACEBUF_NULL (46)
#define TIDL_SAFETY_FLAG_TIDLRT_UTILS_FORCE_PADEDBUF_NULL (47)
#define TIDL_SAFETY_FLAG_TIDLRT_UTILS_FORCE_DMACURIDX_INVALID (48)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_SYNC_INVALID (49)
#define TIDL_SAFETY_FLAG_TIDLRT_ALG_GCINFO_NULL (505)

#define TIDL_SAFETY_FLAG_TIDLRT_UTILS_FORCE_DMACNTX_NULL (60)
#define TIDL_SAFETY_FLAG_ALG_ALLOC_FORCE_PTRWORKLOAD_NULL (61)
#define TIDL_SAFETY_FLAG_WL_EXECINIT_FORCE_DMACURIDX_INVALID (62)
#define TIDL_SAFETY_FLAG_WL_EXECINIT_FORCE_SYSMEMSIZES_ZERO (63)
#define TIDL_SAFETY_FLAG_WL_ALLOCNCMPT_FORCE_FUNCPTR_NULL (64)
#define TIDL_SAFETY_FLAG_WL_WLPROC_FORCE_DMAUTILS_NULL (65)
#define TIDL_SAFETY_FLAG_ALG_PROC_FORCE_INTALGHNDLE_NULL (66)
#define TIDL_SAFETY_FLAG_TIDLRT_UTILS_FORCE_QNTRNG_NULL (67)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_TRACEBUFPTR_NULL (68)
#define TIDL_SAFETY_FLAG_LAYER_INIT_FORCE_LAYERTYPE_INVALID (69)
#define TIDL_SAFETY_FLAG_TIDLRT_UTILS_FORCE_CTRLCALL_TEST (70)
#define TIDL_SAFETY_FLAG_TIDLRT_UTILS_FORCE_PROCCNT_TEST (71)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_NUMODLAYER_INVALID (72)
#define TIDL_SAFETY_FLAG_ALG_PROCESS_FORCE_DMACURIDX_INVALID (73)
#define TIDL_SAFETY_FLAG_WL_XFRLNK_FORCE_DIFFSRCSTAGE_INVALID (74)
#define TIDL_SAFETY_FLAG_WL_XFRLNKINTER_FORCE_FMT16TO8B_INVALID (75)
#define TIDL_SAFETY_FLAG_WL_XFRLNKINTER_FORCE_FMT8TO16B_INVALID (76)
#define TIDL_SAFETY_FLAG_WL_XFRLNKINTER_FORCE_FMT8TO32B_INVALID (77)
#define TIDL_SAFETY_FLAG_TIDLRT_INIT_FORCE_TRACEBUF_NULL (78)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_OPTEXTMEML1_NULL (79)
#define TIDL_SAFETY_FLAG_WL_EXECINIT_FORCE_INITPARAM_NULL (80)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_FORCE_GETPTR_NULL (81)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_FORCE_LNKSUBTYPE_INVALID (82)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_FORCE_SNKSHAPETYPE_INVALID (83)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_FORCE_PADROWS_INVALID (84)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_FORCE_PADCOLS_INVALID (85)
#define TIDL_SAFETY_FLAG_WL_XFRLNK_FORCE_DIFFSRCSTAGE2_INVALID (86)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_FORCE_PADCOLS_REQ_INVALID (87)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_FORCE_1D_INVALID (88)
#define TIDL_SAFETY_FLAG_WL_EXECPROC_DECONV_FORCE_1D_INVALID (89)

#define TIDL_SAFETY_FLAG_CUSTOM_FORCE_INDATAPTR_NULL (90)
#define TIDL_SAFETY_FLAG_CUSTOM_FORCE_OPTIMISEEXTMEM_NULL (91)

#define TIDL_SAFETY_FLAG_CONST_GCHELPERHANDLE_NULL (92)

#define TIDL_SAFETY_FLAG_ALG_LAYERPROCESS_FORCE_REDUCELAYER (100)
#define TIDL_SAFETY_FLAG_ALG_LAYERPROCESS_FORCE_REDUCELAYER_NULL (101)
#define TIDL_SAFETY_FLAG_ALG_LYERINIT_FORCE_STATUS_INVALID (102)
#define TIDL_SAFETY_FLAG_ALG_ALLOC_FORCE_LAYERTYPE_INVALID (103)
#define TIDL_SAFETY_FLAG_ALG_INIT_FORCE_LAYERTYPE_INVALID (104)

#define TIDL_SAFETY_FLAG_WORKLOAD_FORCE_REF_BUF_NOT_FOUND (500)
#define TIDL_SAFETY_FLAG_WORKLOAD_REF_EXEC_GCHELPERHANDLE_NULL (501)
#define TIDL_SAFETY_FLAG_WORKLOAD_REF_EXEC_PBUFLIST_NULL (502)
#define TIDL_SAFETY_FLAG_WORKLOAD_REF_EXEC_TENSORPOSITION_NULL (503)

#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_HANDLE_NULL (1500)
#define TIDL_SAFETY_FLAG_BATCHNORM_NONLUTCORE_FORCE_NETVERSION (1501)
#define TIDL_SAFETY_FLAG_BATCHNORM_FLOATNONLINEAR_FORCE_NETVERSION (1502)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_EXECUTE_POINTER_NULL (1503)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_INIT_LUTPARAMS_MEM_POINTER_NULL (1504)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_WEIGHT_PARAM_ZERO (1505)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_DEVICE_INIT_IALG_EFAIL (1506)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_ERR_INVALID_TYPE (1507)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_REF_BATCHNORM_CORE_ACCMEM_SCRATCH_NULL (1508)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_BATCHNORM_CORE_ERROR_FLOWCTRL (1509)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_BATCHNORM_CORE_ERROR_FLOAT_REFERENCE (1510)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_BATCHNORM_CORE_ERROR_NONLUT_REFERENCE (1511)
#define TIDL_SAFETY_FLAG_BATCHNORM_FORCE_BATCHNORM_CORE_USE_DDR_MEM_FOR_LUT (1512)

#define TIDL_SAFETY_FLAG_POOLING_FORCE_HANDLE_NULL (1000)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_KERNEL_HANDLE_NULL (1001)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_PAD_OTF_FALSE (1002)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_DATATYPE_CHANGE (1003)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_SCRATCH_SIZE (1004)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_SRC_ADDRESS_NULL (1005)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_NEGATIVE_TEST_CI_FLOW (1006)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_FUNC_STYLE_ERROR (1007)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_POOL_TYPE_ERROR (1008)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_WORKLOADUNIT_NULL (1009)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_SRCADDR_32BIT (1010)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_NUMBYTES_3 (1011)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_NUMBYTES_4 (1012)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_NUMBYTES_8 (1013)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_BUFFER_PREDICATE_NULL (1014)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_DST_ADDRESS_NULL (1015)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_ACT_TYPE_ERROR (1017)
#define TIDL_SAFETY_FLAG_POOLING_FORCE_MAX_NUM_OF_LAYERS (1018)

#define TIDL_SAFETY_FLAG_LAYERNORM_NUMBYTES_ERROR (3100)
#define TIDL_SAFETY_FLAG_LAYERNORM_NUMBYTES_ERROR_V2 (3101)
#define TIDL_SAFETY_FLAG_LAYERNORM_NUMBYTES_ERROR_INNERLOOP (3102)
#define TIDL_SAFETY_FLAG_LAYERNORM_SCRATCH_SIZE_ERROR (3103)
#define TIDL_SAFETY_FLAG_LAYERNORM_FORCE_SRC_NULL (3104)
#define TIDL_SAFETY_FLAG_LAYERNORM_NUMBYTES_ERROR_V2_INNERLOOP (3105)
#define TIDL_SAFETY_FLAG_LAYERNORM_FORCE_SRC_NULL_V2 (3106)
#define TIDL_SAFETY_FLAG_LAYERNORM_SCRATCH_SIZE_ERROR_V2 (3107)
#define TIDL_SAFETY_FLAG_LAYERNORM_NUMBYTES_ERROR_C7X (3108)
#define TIDL_SAFETY_FLAG_LAYERNORM_SCRATCH_SIZE_ERROR_C7X (3109)
#define TIDL_SAFETY_FLAG_LAYERNORM_FORCE_NET_VERSION_MODIFY (3110)
#define TIDL_SAFETY_FLAG_LAYERNORM_KERNEL_HANDLE_NULL (3111)
#define TIDL_SAFETY_FLAG_LAYERNORM_FUNC_STYLE_ERROR (3112)
#define TIDL_SAFETY_FLAG_LAYERNORM_NATC_DATATYPE_ERROR (3113)
#define TIDL_SAFETY_FLAG_LAYERNORM_FORCE_BUFFERDATASIZE_MAX (3200)
#define TIDL_SAFETY_FLAG_LAYERNORM_FORCE_SRC_AND_DST_ADDR_NULL (3201)
#define TIDL_SAFETY_FLAG_LAYERNORM_NUMBYTES_ERROR_EXEC (3202)
#define TIDL_SAFETY_FLAG_LAYERNORM_NUMBYTES_ERROR_V2_EXEC (3203)


#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_SRC_NULL_NATC_32BIT_FIXED_NP2_QUANT (3200)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_SRC_NULL_NATC_32BIT_ASYM_NP2_TFL (3201)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_SRCADDR_32BIT (3202)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_FUNC_STYLE_ERROR (3203)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_SRCADDR_32BIT_KERNEL (3204)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_ROUNDBIT_ZERO (3205)

#define TIDL_SAFETY_FLAG_GATHER_FLOAT_ERROR (3300)
#define TIDL_SAFETY_FLAG_GATHER_DATATYPE_ERROR (3301)

#define TIDL_SAFETY_FLAG_SCATTERELEMENTS_FLOAT_INPUT_ERROR (3400)
#define TIDL_SAFETY_FLAG_SCATTERND_AXIS_AND_DATATYPE_ERROR (3401)
#define TIDL_SAFETY_FLAG_SCATTERND_LARGE_NUMLINES_ERROR (3402)
#define TIDL_SAFETY_FLAG_SCATTERELEMENTS_NULL_POINTER_ERROR (3403)
#define TIDL_SAFETY_FLAG_SCATTERELEMENTS_NUMDIM_ERROR (3404)
#define TIDL_SAFETY_FLAG_SCATTERELEMENTS_NUM_OUT_ROW_ERROR (3405)
#define TIDL_SAFETY_FLAG_SCATTERELEMENTS_MEM_FOR_TINY_TABLE_ERROR (3406)

#define TIDL_SAFETY_FLAG_SHUFFLECHANNEL_FORCE_TRMEM1_NULL (2000)
#define TIDL_SAFETY_FLAG_SHUFFLECHANNEL_FORCE_TRMEM2_NULL (2001)
#define TIDL_SAFETY_FLAG_SHUFFLECHANNEL_FORCE_DMA_TR_NULL (2002)
#define TIDL_SAFETY_FLAG_SHUFFLECHANNEL_FORCE_DMA_CONTEXT_NULL (2003)
#define TIDL_SAFETY_FLAG_SHUFFLECHANNEL_FORCE_NUMSPLITS_DMA_TR_NULL (2004)
#define TIDL_SAFETY_FLAG_SHUFFLECHANNEL_FORCE_NUMSPLITS_DMA_CONTEXT_NULL (2005)

#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_SRC_NULL_NATC_32BIT_FIXED_NP2_QUANT (3200)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_SRC_NULL_NATC_32BIT_ASYM_NP2_TFL (3201)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_SRCADDR_32BIT (3202)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_FUNC_STYLE_ERROR (3203)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_SRCADDR_32BIT_KERNEL (3204)
#define TIDL_SAFETY_FLAG_GLOBALAVGPOOL_FORCE_ROUNDBIT_ZERO (3205)

#define TIDL_SAFETY_FLAG_GATHER_FLOAT_ERROR (3300)
#define TIDL_SAFETY_FLAG_GATHER_DATATYPE_ERROR (3301)

#define TIDL_SAFETY_FLAG_RESIZE_FORCE_SOURCE_NULL (4000)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_RESIZEVALUE (4001)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_L3_SCRATCHSIZE_MAX (4002)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_DDR_SCRATCHSIZE_MAX (4003)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_PROCESSNEW_WIDTHRATIO_ZERO (4004)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_PROCESSNEW_HEIGHTRATIO_ZERO (4005)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_PROCESSSP_WIDTHRATIO_ZERO (4006)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_PROCESSSP_HEIGHTRATIO_ZERO (4007)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_FLOWCONTROL (4008)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_INVLID_RESIZE_MODE (4009)
#define TIDL_SAFETY_FLAG_RESIZE_FORCE_DATATYPE_ERROR (4010)


#define TIDL_SAFETY_FLAG_CONCAT_FORCE_SCRATCH_SIZE (4500)
#define TIDL_SAFETY_FLAG_CONCAT_FORCE_SRC_KERNEL_NULL (4501)
#define TIDL_SAFETY_FLAG_CONCAT_FORCE_DST_ADDR_32BIT (4502)
#define TIDL_SAFETY_FLAG_CONCAT_FORCE_KERNEL_32BIT_DATATYPE (4503)
#define TIDL_SAFETY_FLAG_CONCAT_FORCE_KERNEL_32BIT_DATATYPE_EXEC (4504)
#define TIDL_SAFETY_FLAG_CONCAT_FORCE_INCORRECT_PROC_ELEM_SIZE (4505)
#define TIDL_SAFETY_FLAG_CONCAT_FORCE_SRC_AND_DST_ADDR_NULL (4506)


#define TIDL_SAFETY_FLAG_RESHAPE_FORCE_ELEMENTTYPE_MAX (4600)

#define TIDL_SAFETY_FLAG_DATAFLOW_FORCE_WORKLOADUNIT_NULL (4700)
#define TIDL_SAFETY_FLAG_DATAFLOW_FORCE_HANDLESIZE_DDR_MAX (4701)
#define TIDL_SAFETY_FLAG_DATAFLOW_FORCE_WLLOOPITR_NULL (4702)

#define TIDL_SAFETY_FLAG_PAD_FORCE_L2_SCRATCHSIZE_MAX (4800)
#define TIDL_SAFETY_FLAG_PAD_FORCE_L3_SCRATCHSIZE_MAX (4801)

#define TIDL_SAFETY_FLAG_SCATTER_FORCE_OUTPTR_NULL (4900)
#define TIDL_SAFETY_FLAG_SCATTER_FORCE_32B_DATATYPE (4901)

#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_HANDLE_NULL (5000)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_AXIS (5001)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_AXIS_MAX (5002)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_TRANSPOSE (5003)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_MEMPTR_NULL (5004)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_TRANSPOSE_ZERO (5005)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_KERNEL_HANDLE_NULL (5006)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_FUNCSTYLE_ERROR (5007)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_SRCADDR_NULL (5008)
#define TIDL_SAFETY_FLAG_SOFTMAX_FORCE_INSUFFICIENT_SCRATCHMEM_ERROR (5009)

#define TIDL_SAFETY_FLAG_CONV2D_FORCE_SCRATCH_SIZE (5500)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_OUTPTR_NULL (5501)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_OUTDATATYPE (5502)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_INVALID_BIASPTR (5503)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_INVALID_DATATYPE (5504)
#define TIDL_SAFETY_FLAG_CONV2D_DEVICE_FORCE_LAYERSPECIFICPARAMS_WL_NULL (5505)
#define TIDL_SAFETY_FLAG_CONV2D_DEVICE_FORCE_ALGLAYER_WL_NULL (5506)
#define TIDL_SAFETY_FLAG_CONV2D_BASE_FORCE_ALGLAYER_WL_NULL (5507)
#define TIDL_SAFETY_FLAG_CONV_ROWFLOW_SRC_AND_SINK_JOINT_NULL (5508)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_INVALID_CONVTYPE (5509)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_COEFF_SRC_NULL (5510)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_REF_ERROR_FUNCTION (5511)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_REF_INVALID_INDATATYPE (5512)
#define TIDL_SAFETY_FLAG_CONV2D_FORCE_REF_INVALID_OUTDATATYPE (5513)

#define TIDL_SAFETY_FLAG_REDUCE_FORCE_PTRTOSCARTCH_NULL (6000)
#define TIDL_SAFETY_FLAG_REDUCE_FORCE_AXIS_MAX (6001)
#define TIDL_SAFETY_FLAG_REDUCE_FORCE_AXIS_WIDTH (6002)
#define TIDL_SAFETY_FLAG_REDUCE_FORCE_FUNC_STYLE (6003)
#define TIDL_SAFETY_FLAG_REDUCE_FORCE_SRC_DST_ADDR_NULL (6004)

#define TIDL_SAFETY_FLAG_CONCAT_FORCE_NUMINBUFS_ZERO (6500)

#define TIDL_SAFETY_FLAG_MATMUL_FORCE_WORKLOADUNIT_NULL (6700)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_DATATYPE_64B (6701)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_BIASPTR_NULL (6702)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_INELEMENTTYPE_WORD (6703)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_INVALID_SCRATCHSIZE (6704)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_INVALID_INBDATA_DATATYPE (6705)
#define TIDL_SAFETY_FLAG_MATMUL_FORCE_INVALID_SRCBUF_DATA_ID (6706)

#define TIDL_SAFETY_FLAG_INNERPRODUCT_INSUFFICIENT_MEMORY_INFEAT_MAP (6800)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_INSUFFICIENT_MEMORY_KERNEL (6801)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_INSUFFICIENT_MEMORY_BIAS (6802)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_INSUFFICIENT_MEMORY_FOR_HANDLE (6803)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_HANDLE_NULL_INIT_ALLOC (6804)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_INPTR_NULL (6805)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_32BIT_OUTDATA (6806)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_32BIT_INDATA (6807)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_MMALIB_HANDLE_NULL (6808)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_DMA_UTILS_CONTEXT_NULL (6809)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_DMA_UTILS_CONTEXT_3D_CONFIGURE_FAIL (6810)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_DMA_CHANNEL_LIMIT_EXCEEDED (6811)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_DMA_UTILS_CONTEXT_INPUT_3D_DECONFIGURE_FAIL (6812)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_SYSMEMS_L2_NULL_INNER_LOOP (6813)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_DMA_UTILS_CONTEXT_NULL_INNER_LOOP (6814)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_32BIT_INDATA_FOR_BIAS (6815)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_MMALIB_HANDLE_NULL_CHECKPARAMS (6816)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_REF_ERROR_HANDLE_NULL (6817)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_INPTR_INFER_NULL (6818)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_FORCE_ROUNDSAT_MMA_ZERO_SHIFT_BITS (6819)
#define TIDL_SAFETY_FLAG_INNERPRODUCT_INSUFFICIENT_L1_MEMORY (6820)

#define TIDL_SAFETY_FLAG_DECONV_FORCE_8B_BIASPARAMSIZE (7000)
#define TIDL_SAFETY_FLAG_DECONV_FORCE_16B_BIASPARAMSIZE (7001)
#define TIDL_SAFETY_FLAG_DECONV_FORCE_BUFSCRATCHSIZE (7002)
#define TIDL_SAFETY_FLAG_DECONV_FORCE_64B_WEIGHTSELEMENTSIZEINBITS (7003)
#define TIDL_SAFETY_FLAG_DECONV2D_FORCE_REF_INVALID_OUTDATATYPE (7004)

#define TIDL_SAFETY_FLAG_CONV2D_MMA_COLFLOW_FORCE_KERNEL_SETUP_FAIL (7100)
#define TIDL_SAFETY_FLAG_CONV2D_MMA_COLFLOW_FORCE_HIGHPRE_REORDERWEIGHTS_ARGS_MMA_FAIL (7101) 
#define TIDL_SAFETY_FLAG_CONV2D_MMA_COLFLOW_FORCE_REORDERWEIGHTS_ARGS_MMA_FAIL (7102)
#define TIDL_SAFETY_FLAG_CONV2D_MMA_COLFLOW_FORCE_GETWEIGHTADDR_FAIL (7103)
#define TIDL_SAFETY_FLAG_CONV2D_MMA_COLFLOW_FORCE_KERNEL_SETUP_ARGS_VARIANTS_FAIL (7104)
#define TIDL_SAFETY_FLAG_CONV2D_MMA_COLFLOW_FORCE_ZERO_PADCOL_PADROW (7105)

#define TIDL_SAFETY_FLAG_TRANSPOSE_ALLOC_FORCE_NETVERSION (7500)
#define TIDL_SAFETY_FLAG_TRANSPOSE_INIT_FORCE_NETVERSION (7501)
#define TIDL_SAFETY_FLAG_TRANSPOSE_PROCESS_FORCE_NETVERSION (7502)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_SRC_UINT8 (7503)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_SRC_INT8 (7504)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_SRC_UINT16 (7505)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_SRC_INT16 (7506)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_DST_FLOAT (7507)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_INIT_CHECKPARAMS (7508)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_FUNCSTYLE (7509)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_PERM (7510)
#define TIDL_SAFETY_FLAG_TRANSPOSE_FORCE_KERNEL_Collapse_Dimensions (7511)

#define TIDL_SAFETY_FLAG_ARGOP_FORCE_SOURCE_NULL (8000)

#define TIDL_SAFETY_FLAG_BATCHRESHAPE_FORCE_KERNEL_HANDLE_NULL (3000)
#define TIDL_SAFETY_FLAG_BATCHRESHAPE_FORCE_FUNC_STYLE_ERROR (3001)
#define TIDL_SAFETY_FLAG_BATCHRESHAPE_FORCE_KERNEL_SRC_NULL (3002)
#define TIDL_SAFETY_FLAG_BATCHRESHAPE_FORCE_NUMBATCHES_ZERO (3003)
#define TIDL_SAFETY_FLAG_BATCHRESHAPE_FORCE_INBATCH_OUTBATCH_NULL (3004)

#define TIDL_SAFETY_FLAG_COLORCONVERSION_FORCE_KERNEL_HANDLE_NULL (3500)
#define TIDL_SAFETY_FLAG_COLORCONVERSION_FORCE_FUNC_STYLE_ERROR (3501)
#define TIDL_SAFETY_FLAG_COLORCONVERSION_FORCE_KERNEL_SRC_NULL (3502)
#define TIDL_SAFETY_FLAG_COLORCONVERSION_FORCE_KERNEL_SRC_ERROR_TYPE (3503)
#define TIDL_SAFETY_FLAG_COLORCONVERSION_FORCE_KERNEL_DST_ERROR_TYPE (3504)
#define TIDL_SAFETY_FLAG_COLORCONVERSION_FORCE_SRC_AND_DST_ADDR_NULL (3505)

#define TIDL_SAFETY_FLAG_ARGOP_FORCE_FUNCSTYLE (8001)
#define TIDL_SAFETY_FLAG_ARGOP_FORCE_KERNEL_SRC_NULL (8002)
#define TIDL_SAFETY_FLAG_ARGOP_FORCE_KERNEL_SRC_32BIT (8003)
#define TIDL_SAFETY_FLAG_ARGOP_FORCE_KERNEL_DST_32BIT (8004)
#define TIDL_SAFETY_FLAG_ARGOP_FORCE_KERNEL_DST_NULL (8005)

#define TIDL_SAFETY_FLAG_ELTWISE_FORCE_KERNEL_HANDLE_NULL (9000)
#define TIDL_SAFETY_FLAG_ELTWISE_ELTWISETYPE (9001)
#define TIDL_SAFETY_FLAG_ELTWISE_FORCE_FUNC_STYLE (9002)
#define TIDL_SAFETY_FLAG_ELTWISE_FORCE_NUMINDATA (9003)
#define TIDL_SAFETY_FLAG_ELTWISEPROD_FORCE_SRC_NATC_NULL (9004)
#define TIDL_SAFETY_FLAG_ELTWISEPROD_FORCE_DST_NATC_NUMBYTES_ERROR (9005)
#define TIDL_SAFETY_FLAG_ELTWISEMINMAX_FORCE_SRC_NUMBYTES_ERROR (9006)
#define TIDL_SAFETY_FLAG_ELTWISEMINMAX_FORCE_DST_NUMBYTES_ERROR (9007)
#define TIDL_SAFETY_FLAG_ELTWISE_NUMINDATA_ERROR (9008)
#define TIDL_SAFETY_FLAG_ELTWISEMINMAX_INPUT_SIGNED_ERROR_CASE (9009)
#define TIDL_SAFETY_FLAG_ELTWISEADD_NUMBYTES_ERROR_HW_PROC_INIT (9010)
#define TIDL_SAFETY_FLAG_ELTWISEADD_NUMBYTES_ERROR_HW_INIT (9011)
#define TIDL_SAFETY_FLAG_ELTWISEADD_ELTWISE_TYPE_ERROR_HW_PROC_INIT (9012)
#define TIDL_SAFETY_FLAG_ELTWISEADD_ELTWISE_NUMINDATA_ERROR_HW_PROC_INIT (9013)
#define TIDL_SAFETY_FLAG_ELTWISEMINMAX_FORCE_SRC_NATC_NULL (9014)
#define TIDL_SAFETY_FLAG_ELTWISEADD_ELTWISE_NUMINDATA_ERROR_HW_INIT (9015)
#define TIDL_SAFETY_FLAG_ELTWISEADD_FORCE_SRC_NATC_NULL (9016)
#define TIDL_SAFETY_FLAG_ELTWISEADD_FORCE_DSTADDR_NULL (9017)

#define TIDL_SAFETY_FLAG_GRIDSAMPLE_FORCE_DATATYPE_ERROR (10000)
#define TIDL_SAFETY_FLAG_GRIDSAMPLE_FORCE_UNSUPPORTED_MODE (10001)
#define TIDL_SAFETY_FLAG_GRIDSAMPLE_FORCE_SCRATCH_SIZE (10002)
#define TIDL_SAFETY_FLAG_GRIDSAMPLE_FORCE_FUNC_STYLE (10003)
#define TIDL_SAFETY_FLAG_GRIDSAMPLE_FORCE_KERNEL_HANDLE_NULL (10004)

#define TIDL_SAFETY_FLAG_DCN_FORCE_LINK_SOURCE_BUFFER_FM (11001)
#define TIDL_SAFETY_FLAG_DCN_FORCE_PARENT_BUFFER_TYPE_FM (11002)
#define TIDL_SAFETY_FLAG_DCN_FORCE_COEFF_BUFFER_SPACE_L2 (11003)
#define TIDL_SAFETY_FLAG_DCN_FORCE_SCRATCH_SIZE_ZERO (11004)
#define TIDL_SAFETY_FLAG_DCN_FORCE_FUNC_STYLE (11005)
#define TIDL_SAFETY_FLAG_DCN_FORCE_KERNEL_HANDLE_NULL (11006)
#define TIDL_SAFETY_FLAG_DCN_FORCE_INVALID_OFFSET_DIMS (11007)
#define TIDL_SAFETY_FLAG_DCN_FORCE_INVALID_MASK_DIMS (11008)
#define TIDL_SAFETY_FLAG_DCN_FORCE_BIAS_DISABLE (11009)
#define TIDL_SAFETY_FLAG_DCN_FORCE_SMALLER_SCRATCH_SIZE (11010)
#define TIDL_SAFETY_FLAG_DCN_FORCE_DATATYPE_ERROR (11011)
#define TIDL_SAFETY_FLAG_DCN_FORCE_NULL_OUTPTR (11012)
#define TIDL_SAFETY_FLAG_DCN_FORCE_DATATYPENSIZE_ERROR (11013)

#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPKBBOX (9500)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPKSCORE (9501)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPKINDICES (9502)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_NMSKEPTINDICES (9503)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_COUNTMLIST (9504)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_COUNTMLISTACC (9505)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TEMPSCORE (9506)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPMINDICES (9507)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPMINDICESSORTED (9508)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPMSCORE (9509)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPMSCORESORTED (9510)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_PRED (9511)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_FEATMAXMINVAL (9512)
#define TIDL_SAFETY_FLAG_OD_FORCE_MAXSCORE (9513)
#define TIDL_SAFETY_FLAG_OD_FORCE_MINSCORE (9514)
#define TIDL_SAFETY_FLAG_OD_FORCE_CODETYPE (9515)
#define TIDL_SAFETY_FLAG_OD_FORCE_ELEMENTTYPE (9516)
#define TIDL_SAFETY_FLAG_OD_FORCE_HEADSIZE (9517)
#define TIDL_SAFETY_FLAG_OD_FORCE_ELEMENTTYPE_16BIT (9518)
#define TIDL_SAFETY_FLAG_OD_FORCE_ELEMENTTYPE_TIDL_UnsignedDoubleWord (9519)
#define TIDL_SAFETY_FLAG_OD_FORCE_ELEMENTTYPE_TIDL_SinglePrecFloat (9520)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_INIT_CHECKPARAMS (9521)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_FUNCSTYLE (9522)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_SCORECONVERT (9523)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_COUNTM (9524)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_SRC_FLOAT (9525)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_SCORECONVERT_INIT (9526)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_TOPM (9527)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_FilterNotInRangeBox (9528)
#define TIDL_SAFETY_FLAG_OD_FORCE_KERNEL_DATALAYOUT (9529)
#define TIDL_SAFETY_FLAG_OD_FORCE_NULLPTR_TOPKBBOX_INTMEM (9530)
#define TIDL_SAFETY_FLAG_OD_FORCE_TOTCNT_INVALID (9531) 
#define TIDL_SAFETY_FLAG_OD_FORCE_ELEMENTTYPE_16BITV2 (9532)
#define TIDL_SAFETY_FLAG_OD_FORCE_TOTCNTFLT_INVALID (9533)
#define TIDL_SAFETY_FLAG_OD_FORCE_TOTCNTSHORT_INVALID (9534)
#define TIDL_SAFETY_FLAG_OD_FORCE_MINSCOREV2 (9535)
#define TIDL_SAFETY_FLAG_OD_FORCE_TOPMDDR (9536)

#define TIDL_SAFETY_FLAG_TOPK_FORCE_LARGE_K (9600)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_NULLPTR_SCRATCH (9601)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_SRC_UINT8 (9602)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_SRC_INT8 (9603)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_SRC_UINT16 (9604)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_SRC_INT16 (9605)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_DST_FLOAT (9606)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_INIT_CHECKPARAMS (9607)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_FUNCSTYLE (9608)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_AXIS (9609)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_WL_NULL (9610)
#define TIDL_SAFETY_FLAG_TOPK_FORCE_KERNEL_AXIS_INIT (9611)

#endif /* TIDL_FORCENEGATIVETEST_H */


