@startuml

actor  user
participant app_pll
participant PllDrv

user-> app_pll : getPllData
loop for all pll in socPllData
     app_pll ->PllDrv :getPllStatus
     PllDrv -> PllDrv: isPllEnabled
     PllDrv -> PllDrv: getNumHsdivs
     PllDrv -> PllDrv: getPllOutFreq
     PllDrv -> PllDrv: getPllAllHsdivsOutFreq
     PllDrv -> PllDrv: getPllDivs
     PllDrv ->app_pll : return {isEnable ,numHsdiv, freqOut, hsdivOut, settings}
    
end
app_pll ->user : return Pll_status

@enduml
