/********************************************************************
*
* MAIN_VGPIO_MUX INTERRUPT MAP. header file
*
* Copyright (C) 2015-2024 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_MAIN_VGPIO_MUX_INTERRUPT_MAP_H_
#define CSLR_MAIN_VGPIO_MUX_INTERRUPT_MAP_H_

#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: MAIN_VGPIO_MUX
*/

#define CSLR_MAIN_VGPIO_MUX_IN0_GPIO0_GPIO_0                                                       (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_1_GPIO0_GPIO_1                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_10_GPIO0_GPIO_10                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_100_GPIO0_GPIO_100                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_101_GPIO0_GPIO_101                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_102_GPIO0_GPIO_102                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_103_GPIO0_GPIO_103                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_104_GPIO0_GPIO_104                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_105_GPIO0_GPIO_105                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_106_GPIO0_GPIO_106                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_107_GPIO0_GPIO_107                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_108_GPIO0_GPIO_108                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_109_GPIO0_GPIO_109                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_11_GPIO0_GPIO_11                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_110_GPIO0_GPIO_110                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_111_GPIO0_GPIO_111                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_112_GPIO0_GPIO_112                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_113_GPIO0_GPIO_113                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_114_GPIO0_GPIO_114                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_115_GPIO0_GPIO_115                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_116_GPIO0_GPIO_116                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_117_GPIO0_GPIO_117                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_118_GPIO0_GPIO_118                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_119_GPIO0_GPIO_119                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_12_GPIO0_GPIO_12                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_120_GPIO0_GPIO_120                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_121_GPIO0_GPIO_121                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_122_GPIO0_GPIO_122                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_123_GPIO0_GPIO_123                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_124_GPIO0_GPIO_124                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_125_GPIO0_GPIO_125                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_13_GPIO0_GPIO_13                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_14_GPIO0_GPIO_14                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_15_GPIO0_GPIO_15                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_16_GPIO0_GPIO_16                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_17_GPIO0_GPIO_17                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_18_GPIO0_GPIO_18                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_19_GPIO0_GPIO_19                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_2_GPIO0_GPIO_2                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_20_GPIO0_GPIO_20                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_21_GPIO0_GPIO_21                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_22_GPIO0_GPIO_22                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_23_GPIO0_GPIO_23                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_24_GPIO0_GPIO_24                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_25_GPIO0_GPIO_25                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_26_GPIO0_GPIO_26                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_27_GPIO0_GPIO_27                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_28_GPIO0_GPIO_28                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_29_GPIO0_GPIO_29                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_3_GPIO0_GPIO_3                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_30_GPIO0_GPIO_30                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_31_GPIO0_GPIO_31                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_32_GPIO0_GPIO_32                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_33_GPIO0_GPIO_33                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_34_GPIO0_GPIO_34                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_35_GPIO0_GPIO_35                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_36_GPIO0_GPIO_36                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_37_GPIO0_GPIO_37                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_38_GPIO0_GPIO_38                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_39_GPIO0_GPIO_39                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_4_GPIO0_GPIO_4                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_40_GPIO0_GPIO_40                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_41_GPIO0_GPIO_41                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_42_GPIO0_GPIO_42                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_43_GPIO0_GPIO_43                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_44_GPIO0_GPIO_44                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_45_GPIO0_GPIO_45                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_46_GPIO0_GPIO_46                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_47_GPIO0_GPIO_47                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_48_GPIO0_GPIO_48                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_49_GPIO0_GPIO_49                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_5_GPIO0_GPIO_5                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_50_GPIO0_GPIO_50                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_51_GPIO0_GPIO_51                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_52_GPIO0_GPIO_52                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_53_GPIO0_GPIO_53                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_54_GPIO0_GPIO_54                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_55_GPIO0_GPIO_55                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_56_GPIO0_GPIO_56                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_57_GPIO0_GPIO_57                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_58_GPIO0_GPIO_58                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_59_GPIO0_GPIO_59                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_6_GPIO0_GPIO_6                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_60_GPIO0_GPIO_60                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_61_GPIO0_GPIO_61                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_62_GPIO0_GPIO_62                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_63_GPIO0_GPIO_63                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_64_GPIO0_GPIO_64                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_65_GPIO0_GPIO_65                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_66_GPIO0_GPIO_66                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_67_GPIO0_GPIO_67                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_68_GPIO0_GPIO_68                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_69_GPIO0_GPIO_69                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_7_GPIO0_GPIO_7                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_70_GPIO0_GPIO_70                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_71_GPIO0_GPIO_71                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_72_GPIO0_GPIO_72                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_73_GPIO0_GPIO_73                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_74_GPIO0_GPIO_74                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_75_GPIO0_GPIO_75                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_76_GPIO0_GPIO_76                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_77_GPIO0_GPIO_77                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_78_GPIO0_GPIO_78                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_79_GPIO0_GPIO_79                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_8_GPIO0_GPIO_8                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_80_GPIO0_GPIO_80                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_81_GPIO0_GPIO_81                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_82_GPIO0_GPIO_82                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_83_GPIO0_GPIO_83                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_84_GPIO0_GPIO_84                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_85_GPIO0_GPIO_85                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_86_GPIO0_GPIO_86                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_87_GPIO0_GPIO_87                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_88_GPIO0_GPIO_88                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_89_GPIO0_GPIO_89                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_9_GPIO0_GPIO_9                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_90_GPIO0_GPIO_90                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_91_GPIO0_GPIO_91                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_92_GPIO0_GPIO_92                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_93_GPIO0_GPIO_93                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_94_GPIO0_GPIO_94                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_95_GPIO0_GPIO_95                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_96_GPIO0_GPIO_96                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_97_GPIO0_GPIO_97                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_98_GPIO0_GPIO_98                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN0_99_GPIO0_GPIO_99                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_GPIO2_GPIO_0                                                       (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_1_GPIO2_GPIO_1                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_10_GPIO2_GPIO_10                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_100_GPIO2_GPIO_100                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_101_GPIO2_GPIO_101                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_102_GPIO2_GPIO_102                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_103_GPIO2_GPIO_103                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_104_GPIO2_GPIO_104                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_105_GPIO2_GPIO_105                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_106_GPIO2_GPIO_106                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_107_GPIO2_GPIO_107                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_108_GPIO2_GPIO_108                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_109_GPIO2_GPIO_109                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_11_GPIO2_GPIO_11                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_110_GPIO2_GPIO_110                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_111_GPIO2_GPIO_111                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_112_GPIO2_GPIO_112                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_113_GPIO2_GPIO_113                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_114_GPIO2_GPIO_114                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_115_GPIO2_GPIO_115                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_116_GPIO2_GPIO_116                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_117_GPIO2_GPIO_117                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_118_GPIO2_GPIO_118                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_119_GPIO2_GPIO_119                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_12_GPIO2_GPIO_12                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_120_GPIO2_GPIO_120                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_121_GPIO2_GPIO_121                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_122_GPIO2_GPIO_122                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_123_GPIO2_GPIO_123                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_124_GPIO2_GPIO_124                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_125_GPIO2_GPIO_125                                                 (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_13_GPIO2_GPIO_13                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_14_GPIO2_GPIO_14                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_15_GPIO2_GPIO_15                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_16_GPIO2_GPIO_16                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_17_GPIO2_GPIO_17                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_18_GPIO2_GPIO_18                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_19_GPIO2_GPIO_19                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_2_GPIO2_GPIO_2                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_20_GPIO2_GPIO_20                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_21_GPIO2_GPIO_21                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_22_GPIO2_GPIO_22                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_23_GPIO2_GPIO_23                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_24_GPIO2_GPIO_24                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_25_GPIO2_GPIO_25                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_26_GPIO2_GPIO_26                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_27_GPIO2_GPIO_27                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_28_GPIO2_GPIO_28                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_29_GPIO2_GPIO_29                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_3_GPIO2_GPIO_3                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_30_GPIO2_GPIO_30                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_31_GPIO2_GPIO_31                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_32_GPIO2_GPIO_32                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_33_GPIO2_GPIO_33                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_34_GPIO2_GPIO_34                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_35_GPIO2_GPIO_35                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_36_GPIO2_GPIO_36                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_37_GPIO2_GPIO_37                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_38_GPIO2_GPIO_38                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_39_GPIO2_GPIO_39                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_4_GPIO2_GPIO_4                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_40_GPIO2_GPIO_40                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_41_GPIO2_GPIO_41                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_42_GPIO2_GPIO_42                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_43_GPIO2_GPIO_43                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_44_GPIO2_GPIO_44                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_45_GPIO2_GPIO_45                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_46_GPIO2_GPIO_46                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_47_GPIO2_GPIO_47                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_48_GPIO2_GPIO_48                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_49_GPIO2_GPIO_49                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_5_GPIO2_GPIO_5                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_50_GPIO2_GPIO_50                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_51_GPIO2_GPIO_51                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_52_GPIO2_GPIO_52                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_53_GPIO2_GPIO_53                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_54_GPIO2_GPIO_54                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_55_GPIO2_GPIO_55                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_56_GPIO2_GPIO_56                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_57_GPIO2_GPIO_57                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_58_GPIO2_GPIO_58                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_59_GPIO2_GPIO_59                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_6_GPIO2_GPIO_6                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_60_GPIO2_GPIO_60                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_61_GPIO2_GPIO_61                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_62_GPIO2_GPIO_62                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_63_GPIO2_GPIO_63                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_64_GPIO2_GPIO_64                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_65_GPIO2_GPIO_65                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_66_GPIO2_GPIO_66                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_67_GPIO2_GPIO_67                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_68_GPIO2_GPIO_68                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_69_GPIO2_GPIO_69                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_7_GPIO2_GPIO_7                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_70_GPIO2_GPIO_70                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_71_GPIO2_GPIO_71                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_72_GPIO2_GPIO_72                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_73_GPIO2_GPIO_73                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_74_GPIO2_GPIO_74                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_75_GPIO2_GPIO_75                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_76_GPIO2_GPIO_76                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_77_GPIO2_GPIO_77                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_78_GPIO2_GPIO_78                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_79_GPIO2_GPIO_79                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_8_GPIO2_GPIO_8                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_80_GPIO2_GPIO_80                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_81_GPIO2_GPIO_81                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_82_GPIO2_GPIO_82                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_83_GPIO2_GPIO_83                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_84_GPIO2_GPIO_84                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_85_GPIO2_GPIO_85                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_86_GPIO2_GPIO_86                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_87_GPIO2_GPIO_87                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_88_GPIO2_GPIO_88                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_89_GPIO2_GPIO_89                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_9_GPIO2_GPIO_9                                                     (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_90_GPIO2_GPIO_90                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_91_GPIO2_GPIO_91                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_92_GPIO2_GPIO_92                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_93_GPIO2_GPIO_93                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_94_GPIO2_GPIO_94                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_95_GPIO2_GPIO_95                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_96_GPIO2_GPIO_96                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_97_GPIO2_GPIO_97                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_98_GPIO2_GPIO_98                                                   (0U)
#define CSLR_MAIN_VGPIO_MUX_IN1_99_GPIO2_GPIO_99                                                   (0U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_MAIN_VGPIO_MUX_INTERRUPT_MAP_H_ */

