/********************************************************************
*
* R5FSS0_CORE0 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2024 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_R5FSS0_CORE0_INTERRUPT_MAP_H_
#define CSLR_R5FSS0_CORE0_INTERRUPT_MAP_H_

#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: R5FSS0_CORE0
*/

#define CSLR_R5FSS0_CORE0_INTR_CTRL_MMR0_IPC_SET16_IPC_SET_IPCFG_0                                 (0U)
#define CSLR_R5FSS0_CORE0_INTR_SMS0_AESEIP38T_0_AES_SINTREQUEST_P_0                                (1U)
#define CSLR_R5FSS0_CORE0_INTR_SMS0_AESEIP38T_0_AES_SINTREQUEST_S_0                                (2U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_CORE0_EXP_INTR_0                                             (4U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_COMMON0_COMMRX_LEVEL_0_0                                     (5U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_COMMON0_COMMTX_LEVEL_0_0                                     (6U)
#define CSLR_R5FSS0_CORE0_INTR_SA3_SS0_INTAGGR_0_INTAGGR_VINTR_7                                   (7U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_168                             (8U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_169                             (9U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_170                             (10U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_171                             (11U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_172                             (12U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_173                             (13U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_174                             (14U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_175                             (15U)
#define CSLR_R5FSS0_CORE0_INTR_SA3_SS0_SA_UL_0_SA_UL_PKA_0                                         (16U)
#define CSLR_R5FSS0_CORE0_INTR_SA3_SS0_SA_UL_0_SA_UL_TRNG_0                                        (17U)
#define CSLR_R5FSS0_CORE0_INTR_SMS0_TIFS_CBASS_0_FW_EXCEPTION_INTR_0                               (19U)
#define CSLR_R5FSS0_CORE0_INTR_SMS0_COMMON_0_COMBINED_SEC_IN_0                                     (20U)
#define CSLR_R5FSS0_CORE0_INTR_SMS0_HSM_CBASS_0_FW_EXCEPTION_INTR_0                                (21U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER6_INTR_PEND_0                                                  (22U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER7_INTR_PEND_0                                                  (23U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER0_INTR_PEND_0                                                  (24U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER1_INTR_PEND_0                                                  (25U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER2_INTR_PEND_0                                                  (26U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER3_INTR_PEND_0                                                  (27U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER4_INTR_PEND_0                                                  (28U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER5_INTR_PEND_0                                                  (29U)
#define CSLR_R5FSS0_CORE0_INTR_RTI0_INTR_WWD_0                                                     (30U)
#define CSLR_R5FSS0_CORE0_INTR_GLUELOGIC_MCU_CBASS_INTR_ERR_GLUE_OUT_0                             (31U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_16                                     (32U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_17                                     (33U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_18                                     (34U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_19                                     (35U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_20                                     (36U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_21                                     (37U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_22                                     (38U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_23                                     (39U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_24                                     (40U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_25                                     (41U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_26                                     (42U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_27                                     (43U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_28                                     (44U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_29                                     (45U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_30                                     (46U)
#define CSLR_R5FSS0_CORE0_INTR_MAIN_GPIOMUX_INTROUTER0_OUTP_31                                     (47U)
#define CSLR_R5FSS0_CORE0_INTR_CPSW0_CPTS_COMP_0                                                   (48U)
#define CSLR_R5FSS0_CORE0_INTR_RL2_OF_CBA4_0_ERR_LVL_0                                             (49U)
#define CSLR_R5FSS0_CORE0_INTR_AASRC0_INFIFO_LEVEL_0                                               (50U)
#define CSLR_R5FSS0_CORE0_INTR_AASRC0_INGROUP_LEVEL_0                                              (51U)
#define CSLR_R5FSS0_CORE0_INTR_AASRC0_OUTFIFO_LEVEL_0                                              (52U)
#define CSLR_R5FSS0_CORE0_INTR_AASRC0_OUTGROUP_LEVEL_0                                             (53U)
#define CSLR_R5FSS0_CORE0_INTR_AASRC0_ERR_LEVEL_0                                                  (54U)
#define CSLR_R5FSS0_CORE0_INTR_AASRC1_INFIFO_LEVEL_0                                               (55U)
#define CSLR_R5FSS0_CORE0_INTR_AASRC1_INGROUP_LEVEL_0                                              (56U)
#define CSLR_R5FSS0_CORE0_INTR_AASRC1_OUTFIFO_LEVEL_0                                              (57U)
#define CSLR_R5FSS0_CORE0_INTR_AASRC1_OUTGROUP_LEVEL_0                                             (58U)
#define CSLR_R5FSS0_CORE0_INTR_AASRC1_ERR_LEVEL_0                                                  (59U)
#define CSLR_R5FSS0_CORE0_INTR_MLB0_MLBSS_MLB_INT_0                                                (60U)
#define CSLR_R5FSS0_CORE0_INTR_MLB0_MLBSS_MLB_AHB_INT_0                                            (61U)
#define CSLR_R5FSS0_CORE0_INTR_MLB0_MLBSS_MLB_AHB_INT_1                                            (62U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_152                             (64U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_153                             (65U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_154                             (66U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_155                             (67U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_156                             (68U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_157                             (69U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_158                             (70U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_159                             (71U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_160                             (72U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_161                             (73U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_162                             (74U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_163                             (75U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_164                             (76U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_165                             (77U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_166                             (78U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_167                             (79U)
#define CSLR_R5FSS0_CORE0_INTR_EPWM0_EPWM_TRIPZINT_0                                               (80U)
#define CSLR_R5FSS0_CORE0_INTR_EPWM1_EPWM_TRIPZINT_0                                               (81U)
#define CSLR_R5FSS0_CORE0_INTR_EPWM2_EPWM_TRIPZINT_0                                               (82U)
#define CSLR_R5FSS0_CORE0_INTR_ECAP0_ECAP_INT_0                                                    (83U)
#define CSLR_R5FSS0_CORE0_INTR_ECAP1_ECAP_INT_0                                                    (84U)
#define CSLR_R5FSS0_CORE0_INTR_ECAP2_ECAP_INT_0                                                    (85U)
#define CSLR_R5FSS0_CORE0_INTR_ECAP3_ECAP_INT_0                                                    (86U)
#define CSLR_R5FSS0_CORE0_INTR_ECAP4_ECAP_INT_0                                                    (87U)
#define CSLR_R5FSS0_CORE0_INTR_ECAP5_ECAP_INT_0                                                    (88U)
#ifdef CSL_MODIFICATION
#define CSLR_R5FSS0_CORE0_INTR_RL2_OF_CBA4_0_ERR_LVL_0                                             (89U)
#define CSLR_R5FSS0_CORE0_INTR_RL2_OF_CBA4_1_ERR_LVL_0                                             (90U)
#define CSLR_R5FSS0_CORE0_INTR_RL2_OF_CBA4_2_ERR_LVL_0                                             (91U)
#define CSLR_R5FSS0_CORE0_INTR_RL2_OF_CBA4_3_ERR_LVL_0                                             (92U)
#endif
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_CORE1_PMU_0                                                  (93U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_CORE0_PMU_0                                                  (94U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_CORE0_VALFIQ_0                                               (95U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_CORE0_VALIRQ_0                                               (96U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_RTCSS0_RTC_EVENT_PEND_0                                        (97U)
#define CSLR_R5FSS0_CORE0_INTR_EFUSE0_EFC_ERROR_0                                                  (98U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCU_GPIOMUX_INTROUTER0_OUTP_16                                  (100U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCU_GPIOMUX_INTROUTER0_OUTP_17                                  (101U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCU_GPIOMUX_INTROUTER0_OUTP_18                                  (102U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCU_GPIOMUX_INTROUTER0_OUTP_19                                  (103U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCU_GPIOMUX_INTROUTER0_OUTP_20                                  (104U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCU_GPIOMUX_INTROUTER0_OUTP_21                                  (105U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCU_GPIOMUX_INTROUTER0_OUTP_22                                  (106U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCU_GPIOMUX_INTROUTER0_OUTP_23                                  (107U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_DCC0_INTR_DONE_LEVEL_0                                          (108U)
#define CSLR_R5FSS0_CORE0_INTR_GLUELOGIC_MAIN_DCC_DONE_GLUE_DCC_DONE_0                             (109U)
#define CSLR_R5FSS0_CORE0_INTR_SMS0_RAT_1_EXP_INTR_0                                               (111U)
#define CSLR_R5FSS0_CORE0_INTR_SMS0_RAT_0_EXP_INTR_0                                               (112U)
#define CSLR_R5FSS0_CORE0_INTR_GLUELOGIC_MAIN_PBIST_CPU_GLUE_OUT_0                                 (113U)
#define CSLR_R5FSS0_CORE0_INTR_GLUELOGIC_WKUP_PBIST_CPUINTR_OUT_0                                  (114U)
#define CSLR_R5FSS0_CORE0_INTR_MCRC64_0_INT_MCRC_0                                                 (119U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP0_REC_INTR_PEND_0                                              (120U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP0_XMIT_INTR_PEND_0                                             (121U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP1_REC_INTR_PEND_0                                              (122U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP1_XMIT_INTR_PEND_0                                             (123U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP2_REC_INTR_PEND_0                                              (124U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP2_XMIT_INTR_PEND_0                                             (125U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP3_REC_INTR_PEND_0                                              (126U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP3_XMIT_INTR_PEND_0                                             (127U)
#define CSLR_R5FSS0_CORE0_INTR_GLUELOGIC_SOC_ACCESS_ERR_INTR_GLUE_OUT_0                            (128U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP4_REC_INTR_PEND_0                                              (130U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP4_XMIT_INTR_PEND_0                                             (131U)
#define CSLR_R5FSS0_CORE0_INTR_CPSW0_EVNT_PEND_0                                                   (134U)
#define CSLR_R5FSS0_CORE0_INTR_CPSW0_MDIO_PEND_0                                                   (135U)
#define CSLR_R5FSS0_CORE0_INTR_CPSW0_STAT_PEND_0                                                   (136U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_DCC1_INTR_DONE_LEVEL_0                                          (137U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_ESM0_ESM_INT_CFG_LVL_0                                         (140U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_ESM0_ESM_INT_HI_LVL_0                                          (141U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_ESM0_ESM_INT_LOW_LVL_0                                         (142U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_PSC0_PSC_ALLINT_0                                              (145U)
#define CSLR_R5FSS0_CORE0_INTR_PSCSS0_PSC_ALLINT_0                                                 (146U)
#define CSLR_R5FSS0_CORE0_INTR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_CBASS_AGG_ERR_INTR_0         (147U)
#define CSLR_R5FSS0_CORE0_INTR_ADC0_GEN_LEVEL_0                                                    (151U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_176                             (153U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_177                             (154U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_178                             (155U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_179                             (156U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_180                             (157U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_181                             (158U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_182                             (159U)
#define CSLR_R5FSS0_CORE0_INTR_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_183                             (160U)
#define CSLR_R5FSS0_CORE0_INTR_MMCSD0_EMMCSDSS_INTR_0                                              (161U)
#define CSLR_R5FSS0_CORE0_INTR_ESM0_ESM_INT_CFG_LVL_0                                              (167U)
#define CSLR_R5FSS0_CORE0_INTR_ESM0_ESM_INT_HI_LVL_0                                               (168U)
#define CSLR_R5FSS0_CORE0_INTR_ESM0_ESM_INT_LOW_LVL_0                                              (169U)
#define CSLR_R5FSS0_CORE0_INTR_FSS0_OSPI0_LVL_INTR_0                                               (171U)
#define CSLR_R5FSS0_CORE0_INTR_FSS0_FSAS_FOTA_STAT_INTR_PEND_0                                     (172U)
#define CSLR_R5FSS0_CORE0_INTR_FSS0_FSAS_FOTA_STAT_ERR_PEND_0                                      (173U)
#define CSLR_R5FSS0_CORE0_INTR_FSS0_OTFA_INTR_ERR_PEND_0                                           (174U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_CORE0_CTI_0                                                  (175U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_CORE1_CTI_0                                                  (176U)
#define CSLR_R5FSS0_CORE0_INTR_DDPA0_DDPA_INTR_0                                                   (177U)
#define CSLR_R5FSS0_CORE0_INTR_FSS1_OSPI_0_OSPI_LVL_INTR_0                                         (178U)
#define CSLR_R5FSS0_CORE0_INTR_FSS1_HYPERBUS1P0_0_HPB_INTR_0                                       (179U)
#define CSLR_R5FSS0_CORE0_INTR_FSS1_FSAS_0_OTFA_INTR_ERR_PEND_0                                    (180U)
#define CSLR_R5FSS0_CORE0_INTR_FSS1_FSAS_0_ECC_INTR_ERR_PEND_0                                     (181U)
#define CSLR_R5FSS0_CORE0_INTR_FSS0_FSAS_ECC_INTR_ERR_PEND_0                                       (182U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_VTM0_THERM_LVL_GT_TH1_INTR_0                                   (183U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_VTM0_THERM_LVL_GT_TH2_INTR_0                                   (184U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_VTM0_THERM_LVL_LT_TH0_INTR_0                                   (185U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN0_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (186U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN2_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (187U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN3_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (188U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN4_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (189U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_I2C0_POINTRPEND_0                                              (190U)
#define CSLR_R5FSS0_CORE0_INTR_I2C0_POINTRPEND_0                                                   (193U)
#define CSLR_R5FSS0_CORE0_INTR_I2C1_POINTRPEND_0                                                   (194U)
#define CSLR_R5FSS0_CORE0_INTR_I2C2_POINTRPEND_0                                                   (195U)
#define CSLR_R5FSS0_CORE0_INTR_I2C3_POINTRPEND_0                                                   (196U)
#define CSLR_R5FSS0_CORE0_INTR_I2C4_POINTRPEND_0                                                   (197U)
#define CSLR_R5FSS0_CORE0_INTR_I2C5_POINTRPEND_0                                                   (198U)
#define CSLR_R5FSS0_CORE0_INTR_I2C6_POINTRPEND_0                                                   (199U)
#define CSLR_R5FSS0_CORE0_INTR_DEBUGSS0_AQCMPINTR_LEVEL_0                                          (201U)
#define CSLR_R5FSS0_CORE0_INTR_DEBUGSS0_CTM_LEVEL_0                                                (202U)
#define CSLR_R5FSS0_CORE0_INTR_GLUELOGIC_EXT_INTN_GLUE_OUT_0                                       (203U)
#define CSLR_R5FSS0_CORE0_INTR_MCSPI0_INTR_SPI_0                                                   (204U)
#define CSLR_R5FSS0_CORE0_INTR_MCSPI1_INTR_SPI_0                                                   (205U)
#define CSLR_R5FSS0_CORE0_INTR_MCSPI2_INTR_SPI_0                                                   (206U)
#define CSLR_R5FSS0_CORE0_INTR_MCSPI3_INTR_SPI_0                                                   (207U)
#define CSLR_R5FSS0_CORE0_INTR_MCSPI4_INTR_SPI_0                                                   (208U)
#define CSLR_R5FSS0_CORE0_INTR_UART0_USART_IRQ_0                                                   (210U)
#define CSLR_R5FSS0_CORE0_INTR_UART1_USART_IRQ_0                                                   (211U)
#define CSLR_R5FSS0_CORE0_INTR_UART2_USART_IRQ_0                                                   (212U)
#define CSLR_R5FSS0_CORE0_INTR_UART3_USART_IRQ_0                                                   (213U)
#define CSLR_R5FSS0_CORE0_INTR_UART4_USART_IRQ_0                                                   (214U)
#define CSLR_R5FSS0_CORE0_INTR_UART5_USART_IRQ_0                                                   (215U)
#define CSLR_R5FSS0_CORE0_INTR_UART6_USART_IRQ_0                                                   (216U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_UART0_USART_IRQ_0                                              (219U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_0                                                          (220U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_1                                                          (221U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_2                                                          (222U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_3                                                          (223U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_4                                                          (224U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_5                                                          (225U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_6                                                          (226U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_7                                                          (227U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_MISC_LEVEL_0                                                   (228U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN1_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (229U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN0_MCANSS_MCAN_LVL_INT_0                                         (230U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN0_MCANSS_MCAN_LVL_INT_1                                         (231U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN1_MCANSS_MCAN_LVL_INT_0                                         (232U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN1_MCANSS_MCAN_LVL_INT_1                                         (233U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN2_MCANSS_MCAN_LVL_INT_0                                         (234U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN2_MCANSS_MCAN_LVL_INT_1                                         (235U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN3_MCANSS_MCAN_LVL_INT_0                                         (236U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN3_MCANSS_MCAN_LVL_INT_1                                         (237U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN4_MCANSS_MCAN_LVL_INT_0                                         (238U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN4_MCANSS_MCAN_LVL_INT_1                                         (239U)
#define CSLR_R5FSS0_CORE0_INTR_MAILBOX0_MAILBOX_CLUSTER_0_MAILBOX_CLUSTER_PEND_0                   (240U)
#define CSLR_R5FSS0_CORE0_INTR_MAILBOX0_MAILBOX_CLUSTER_1_MAILBOX_CLUSTER_PEND_0                   (241U)
#define CSLR_R5FSS0_CORE0_INTR_MAILBOX0_MAILBOX_CLUSTER_3_MAILBOX_CLUSTER_PEND_0                   (242U)
#define CSLR_R5FSS0_CORE0_INTR_MAILBOX0_MAILBOX_CLUSTER_5_MAILBOX_CLUSTER_PEND_1                   (243U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_0                                (248U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_1                                (249U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_2                                (250U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_3                                (251U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_4                                (252U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_5                                (253U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_6                                (254U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V0_CLEC_SOC_EVENTS_OUT_LEVEL_7                                (255U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V1_CLEC_SOC_EVENTS_OUT_LEVEL_0                                (256U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V1_CLEC_SOC_EVENTS_OUT_LEVEL_1                                (257U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V1_CLEC_SOC_EVENTS_OUT_LEVEL_2                                (258U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V1_CLEC_SOC_EVENTS_OUT_LEVEL_3                                (259U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V1_CLEC_SOC_EVENTS_OUT_LEVEL_4                                (260U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V1_CLEC_SOC_EVENTS_OUT_LEVEL_5                                (261U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V1_CLEC_SOC_EVENTS_OUT_LEVEL_6                                (262U)
#define CSLR_R5FSS0_CORE0_INTR_C7X256V1_CLEC_SOC_EVENTS_OUT_LEVEL_7                                (263U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER8_INTR_PEND_0                                                  (264U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER9_INTR_PEND_0                                                  (265U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER10_INTR_PEND_0                                                 (266U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER11_INTR_PEND_0                                                 (267U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER12_INTR_PEND_0                                                 (268U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER13_INTR_PEND_0                                                 (269U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER14_INTR_PEND_0                                                 (270U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER15_INTR_PEND_0                                                 (271U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_R5FSS0_CORE0_INTERRUPT_MAP_H_ */

