/********************************************************************
*
* ESM0 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2024 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_ESM0_INTERRUPT_MAP_H_
#define CSLR_ESM0_INTERRUPT_MAP_H_

#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: ESM0
*/

#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_CBASS0_DEFAULT_EXP_0                                          (0U)
#define CSLR_ESM0_ESM_LVL_EVENT_ECC_AGGR0_UNCORR_LEVEL_0                                           (1U)
#define CSLR_ESM0_ESM_LVL_EVENT_ECC_AGGR0_CORR_LEVEL_0                                             (2U)
#define CSLR_ESM0_ESM_LVL_EVENT_CPSW0_ECC_SEC_PEND_0                                               (3U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_RAT_0_EXP_INTR_0                                              (4U)
#define CSLR_ESM0_ESM_LVL_EVENT_CBASS_MISC_PERI0_DEFAULT_EXP_0                                     (5U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS0_CORE1_EXP_INTR_0                                            (6U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_PSRAMECC_8K0_ECC_CORR_LEVEL_0                                 (8U)
#define CSLR_ESM0_ESM_LVL_EVENT_DMASS0_ECC_AGGR_0_ECC_CORRECTED_ERR_LEVEL_0                        (9U)
#define CSLR_ESM0_ESM_LVL_EVENT_DMASS0_ECC_AGGR_0_ECC_UNCORRECTED_ERR_LEVEL_0                      (10U)
#define CSLR_ESM0_ESM_LVL_EVENT_FSS0_OSPI0_ECC_CORR_LVL_INTR_0                                     (11U)
#define CSLR_ESM0_ESM_LVL_EVENT_FSS1_OSPI_ECC_AGGR_0_OSPI_ECC_CORR_LVL_INTR_0                      (12U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_PSRAMECC_8K0_ECC_UNCORR_LEVEL_0                               (13U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_RAT_1_EXP_INTR_0                                              (14U)
#define CSLR_ESM0_ESM_LVL_EVENT_PDMA0_ECC_SEC_PEND_0                                               (15U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_PSRAM2KX32E0_ECC_CORR_LEVEL_0                                 (16U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_PSRAM2KX32E0_ECC_UNCORR_LEVEL_0                               (17U)
#define CSLR_ESM0_ESM_LVL_EVENT_PLLFRACF2_SSMOD7_LOCKLOSS_IPCFG_0                                  (18U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_ECC_AGGR0_CORR_LEVEL_0                                        (20U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_ECC_AGGR0_UNCORR_LEVEL_0                                      (21U)
#define CSLR_ESM0_ESM_LVL_EVENT_ECC_AGGR2_CORR_LEVEL_0                                             (24U)
#define CSLR_ESM0_ESM_LVL_EVENT_ECC_AGGR2_UNCORR_LEVEL_0                                           (25U)
#define CSLR_ESM0_ESM_LVL_EVENT_ECC_AGGR3_CORR_LEVEL_0                                             (26U)
#define CSLR_ESM0_ESM_LVL_EVENT_ECC_AGGR3_UNCORR_LEVEL_0                                           (27U)
#define CSLR_ESM0_ESM_LVL_EVENT_PDMA1_ECC_SEC_PEND_0                                               (28U)
#define CSLR_ESM0_ESM_LVL_EVENT_PSRAMECC0_ECC_CORR_LEVEL_0                                         (29U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_R5FSS0_CORE0_ECC_CORRECTED_LEVEL_0                            (30U)
#define CSLR_ESM0_ESM_LVL_EVENT_USB0_HOST_SYSTEM_ERROR_0                                           (32U)
#define CSLR_ESM0_ESM_LVL_EVENT_ADC0_ECC_CORRECTED_ERR_LEVEL_0                                     (33U)
#define CSLR_ESM0_ESM_LVL_EVENT_ADC0_ECC_UNCORRECTED_ERR_LEVEL_0                                   (34U)
#define CSLR_ESM0_ESM_LVL_EVENT_USB0_A_ECC_AGGR_CORRECTED_ERR_LEVEL_0                              (35U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_ESM0_ESM_INT_CFG_LVL_0                                        (37U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_ESM0_ESM_INT_HI_LVL_0                                         (38U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_ESM0_ESM_INT_LOW_LVL_0                                        (39U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_R5FSS0_COMMON0_ECC_DE_TO_ESM_0_0                              (40U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_R5FSS0_COMMON0_ECC_SE_TO_ESM_0_0                              (41U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS1_CORE0_ECC_AGGR_ECC_CORRECTED_LEVEL_0                        (42U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS1_CORE0_ECC_AGGR_ECC_UNCORRECTED_LEVEL_0                      (43U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS1_CORE1_ECC_AGGR_ECC_CORRECTED_LEVEL_0                        (44U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS1_CORE1_ECC_AGGR_ECC_UNCORRECTED_LEVEL_0                      (45U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS1_COMMON0_ECC_DE_TO_ESM_0_0                                   (46U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS1_COMMON0_ECC_DE_TO_ESM_1_0                                   (47U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS1_COMMON0_ECC_SE_TO_ESM_0_0                                   (48U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS1_COMMON0_ECC_SE_TO_ESM_1_0                                   (49U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_DMTIMER_0_INTR_PEND_0                                         (50U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_DMTIMER_1_INTR_PEND_0                                         (51U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_DMTIMER_2_INTR_PEND_0                                         (52U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_DMTIMER_3_INTR_PEND_0                                         (53U)
#define CSLR_ESM0_ESM_LVL_EVENT_MMCSD0_EMMCSDSS_RXMEM_CORR_ERR_LVL_0                               (54U)
#define CSLR_ESM0_ESM_LVL_EVENT_MMCSD0_EMMCSDSS_RXMEM_UNCORR_ERR_LVL_0                             (55U)
#define CSLR_ESM0_ESM_LVL_EVENT_MMCSD0_EMMCSDSS_TXMEM_CORR_ERR_LVL_0                               (56U)
#define CSLR_ESM0_ESM_LVL_EVENT_MMCSD0_EMMCSDSS_TXMEM_UNCORR_ERR_LVL_0                             (57U)
#define CSLR_ESM0_ESM_LVL_EVENT_MCAN0_MCANSS_ECC_CORR_LVL_INT_0                                    (58U)
#define CSLR_ESM0_ESM_LVL_EVENT_MCAN0_MCANSS_ECC_UNCORR_LVL_INT_0                                  (59U)
#define CSLR_ESM0_ESM_LVL_EVENT_MCAN1_MCANSS_ECC_CORR_LVL_INT_0                                    (60U)
#define CSLR_ESM0_ESM_LVL_EVENT_MCAN1_MCANSS_ECC_UNCORR_LVL_INT_0                                  (61U)
#define CSLR_ESM0_ESM_LVL_EVENT_MCAN2_MCANSS_ECC_CORR_LVL_INT_0                                    (62U)
#define CSLR_ESM0_ESM_LVL_EVENT_MCAN2_MCANSS_ECC_UNCORR_LVL_INT_0                                  (63U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V1_CLEC_DFT_PBIST_SAFETY_ERROR_0                             (64U)
#define CSLR_ESM0_ESM_LVL_EVENT_PDMA4_ECC_SEC_PEND_0                                               (65U)
#define CSLR_ESM0_ESM_LVL_EVENT_PDMA4_ECC_DED_PEND_0                                               (66U)
#define CSLR_ESM0_ESM_LVL_EVENT_CPSW0_ECC_DED_PEND_0                                               (67U)
#define CSLR_ESM0_ESM_LVL_EVENT_MCAN3_MCANSS_ECC_CORR_LVL_INT_0                                    (68U)
#define CSLR_ESM0_ESM_LVL_EVENT_MCAN3_MCANSS_ECC_UNCORR_LVL_INT_0                                  (69U)
#define CSLR_ESM0_ESM_LVL_EVENT_MCAN4_MCANSS_ECC_CORR_LVL_INT_0                                    (70U)
#define CSLR_ESM0_ESM_LVL_EVENT_MCAN4_MCANSS_ECC_UNCORR_LVL_INT_0                                  (71U)
#define CSLR_ESM0_ESM_LVL_EVENT_DCC7_INTR_ERR_LEVEL_0                                              (73U)
#define CSLR_ESM0_ESM_LVL_EVENT_FSS0_OSPI0_ECC_UNCORR_LVL_INTR_0                                   (74U)
#define CSLR_ESM0_ESM_LVL_EVENT_FSS1_OSPI_ECC_AGGR_0_OSPI_ECC_UNCORR_LVL_INTR_0                    (75U)
#define CSLR_ESM0_ESM_LVL_EVENT_CBASS_INFRA1_DEFAULT_EXP_0                                         (76U)
#define CSLR_ESM0_ESM_LVL_EVENT_MLB0_MLBSS_ECC_CORR_LVL_0                                          (77U)
#define CSLR_ESM0_ESM_LVL_EVENT_MLB0_MLBSS_ECC_UNCORR_LVL_0                                        (78U)
#define CSLR_ESM0_ESM_LVL_EVENT_DCC6_INTR_ERR_LEVEL_0                                              (79U)
#define CSLR_ESM0_ESM_LVL_EVENT_CBASS_CENTRAL2_DEFAULT_EXP_0                                       (80U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_RTI_1_WDG_INTR_0                                              (81U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_RTI_1_WDG_INTR_1                                              (82U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_RTI_1_WDG_INTR_2                                              (83U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_RTI_1_WDG_INTR_3                                              (84U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_RTI_1_WDG_INTR_4                                              (85U)
#define CSLR_ESM0_ESM_LVL_EVENT_CBASS0_DEFAULT_EXP_0                                               (86U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_RTI_0_WDG_INTR_0                                              (87U)
#define CSLR_ESM0_ESM_LVL_EVENT_PDMA0_ECC_DED_PEND_0                                               (88U)
#define CSLR_ESM0_ESM_LVL_EVENT_PDMA1_ECC_DED_PEND_0                                               (89U)
#define CSLR_ESM0_ESM_LVL_EVENT_PSRAMECC0_ECC_UNCORR_LEVEL_0                                       (90U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_R5FSS0_CORE0_ECC_UNCORRECTED_LEVEL_0                          (91U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_RTI_0_WDG_INTR_1                                              (92U)
#define CSLR_ESM0_ESM_LVL_EVENT_CBASS_MEM0_DEFAULT_EXP_0                                           (93U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_RTI_0_WDG_INTR_2                                              (96U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_RTI_0_WDG_INTR_3                                              (97U)
#define CSLR_ESM0_ESM_LVL_EVENT_DFTSS0_DFT_SAFETY_123_0                                            (98U)
#define CSLR_ESM0_ESM_LVL_EVENT_DFTSS0_DFT_SAFETY_MULTI_0                                          (99U)
#define CSLR_ESM0_ESM_LVL_EVENT_DFTSS0_DFT_SAFETY_ONE_0                                            (100U)
#define CSLR_ESM0_ESM_LVL_EVENT_MCU_MCU0_VDD_CORE_GLDTC_STAT_THRESH_HI_FLAG_IPCFG_0                (101U)
#define CSLR_ESM0_ESM_LVL_EVENT_MCU_MCU0_VDD_CORE_GLDTC_STAT_THRESH_LOW_FLAG_IPCFG_0               (102U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_RTI_0_WDG_INTR_4                                              (103U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_ECC_AGGR1_CORR_LEVEL_0                                        (104U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_ECC_AGGR1_UNCORR_LEVEL_0                                      (105U)
#define CSLR_ESM0_ESM_LVL_EVENT_AM275_MAIN_IPCSS_CBASS0_DEFAULT_EXP_0                              (110U)
#define CSLR_ESM0_ESM_LVL_EVENT_USB0_A_ECC_AGGR_UNCORRECTED_ERR_LEVEL_0                            (111U)
#define CSLR_ESM0_ESM_LVL_EVENT_DCC0_INTR_ERR_LEVEL_0                                              (112U)
#define CSLR_ESM0_ESM_LVL_EVENT_DCC1_INTR_ERR_LEVEL_0                                              (113U)
#define CSLR_ESM0_ESM_LVL_EVENT_DCC2_INTR_ERR_LEVEL_0                                              (114U)
#define CSLR_ESM0_ESM_LVL_EVENT_DCC3_INTR_ERR_LEVEL_0                                              (115U)
#define CSLR_ESM0_ESM_LVL_EVENT_DCC4_INTR_ERR_LEVEL_0                                              (116U)
#define CSLR_ESM0_ESM_LVL_EVENT_DCC5_INTR_ERR_LEVEL_0                                              (117U)
#define CSLR_ESM0_ESM_LVL_EVENT_SA3_SS0_DMSS_ECCAGGR_0_DMSS_ECC_DED_PEND_0                         (118U)
#define CSLR_ESM0_ESM_LVL_EVENT_SA3_SS0_DMSS_ECCAGGR_0_DMSS_ECC_SEC_PEND_0                         (119U)
#define CSLR_ESM0_ESM_LVL_EVENT_SA3_SS0_SA_UL_0_SA_UL_ECC_CORR_LEVEL_0                             (120U)
#define CSLR_ESM0_ESM_LVL_EVENT_SA3_SS0_SA_UL_0_SA_UL_ECC_UNCORR_LEVEL_0                           (121U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_R5FSS0_CORE0_EXP_INTR_0                                       (124U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS1_CORE0_EXP_INTR_0                                            (126U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS1_CORE1_EXP_INTR_0                                            (127U)
#define CSLR_ESM0_ESM_LVL_EVENT_PLLFRACF2_SSMOD0_LOCKLOSS_IPCFG_0                                  (128U)
#define CSLR_ESM0_ESM_LVL_EVENT_PLLFRACF2_SSMOD1_LOCKLOSS_IPCFG_0                                  (129U)
#define CSLR_ESM0_ESM_LVL_EVENT_PLLFRACF2_SSMOD2_LOCKLOSS_IPCFG_0                                  (130U)
#define CSLR_ESM0_ESM_LVL_EVENT_PLLFRACF2_SSMOD4_LOCKLOSS_IPCFG_0                                  (131U)
#define CSLR_ESM0_ESM_LVL_EVENT_PLLFRACF2_SSMOD14_LOCKLOSS_IPCFG_0                                 (132U)
#define CSLR_ESM0_ESM_LVL_EVENT_PLLFRACF2_SSMOD15_LOCKLOSS_IPCFG_0                                 (133U)
#define CSLR_ESM0_ESM_LVL_EVENT_MCU_PLLFRACF2_SSMOD0_LOCKLOSS_IPCFG_0                              (134U)
#define CSLR_ESM0_ESM_LVL_EVENT_GLUELOGIC_HFOSC0_CLKLOSS_GLUE_REF_CLK_LOSS_DETECT_OUT_0            (135U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_VTM0_THERM_LVL_LT_TH0_INTR_0                                  (136U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_VTM0_THERM_LVL_GT_TH1_INTR_0                                  (137U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_VTM0_THERM_LVL_GT_TH2_INTR_0                                  (138U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_VTM0_CORR_LEVEL_0                                             (139U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_VTM0_UNCORR_LEVEL_0                                           (140U)
#define CSLR_ESM0_ESM_LVL_EVENT_FSS0_FSAS_ECC_INTR_ERR_PEND_0                                      (141U)
#define CSLR_ESM0_ESM_LVL_EVENT_FSS1_FSAS_0_ECC_INTR_ERR_PEND_0                                    (142U)
#define CSLR_ESM0_ESM_LVL_EVENT_FSS1_HYPERBUS_ECC_AGGR_0_HPB_ECC_CORR_LEVEL_0                      (143U)
#define CSLR_ESM0_ESM_LVL_EVENT_FSS1_HYPERBUS_ECC_AGGR_0_HPB_ECC_UNCORR_LEVEL_0                    (144U)
#define CSLR_ESM0_ESM_LVL_EVENT_FSS0_ECC_CORR_LEVEL_0                                              (145U)
#define CSLR_ESM0_ESM_LVL_EVENT_FSS0_ECC_UNCORR_LEVEL_0                                            (146U)
#define CSLR_ESM0_ESM_LVL_EVENT_FSS1_MISC_0_ECC_INTR_ERR_PEND_0                                    (147U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V0_CLEC_DFT_PBIST_SAFETY_ERROR_0                             (149U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_HSM_ECC_AGGR_0_ECC_CORRECTED_LEVEL_0                          (150U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_HSM_ECC_AGGR_0_ECC_UNCORRECTED_LEVEL_0                        (151U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_TIFS_ECC_AGGR_0_ECC_CORRECTED_LEVEL_0                         (153U)
#define CSLR_ESM0_ESM_LVL_EVENT_SMS0_TIFS_ECC_AGGR_0_ECC_UNCORRECTED_LEVEL_0                       (154U)
#define CSLR_ESM0_ESM_LVL_EVENT_PBIST0_DFT_PBIST_SAFETY_ERROR_0                                    (157U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_PBIST0_DFT_PBIST_SAFETY_ERROR_0                               (158U)
#define CSLR_ESM0_ESM_LVL_EVENT_WKUP_PBIST1_DFT_PBIST_SAFETY_ERROR_0                               (159U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V0_CLEC_ESM_EVENTS_OUT_LEVEL_0                               (160U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V0_CLEC_ESM_EVENTS_OUT_LEVEL_1                               (161U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V0_CLEC_ESM_EVENTS_OUT_LEVEL_2                               (162U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V0_CLEC_ESM_EVENTS_OUT_LEVEL_3                               (163U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V0_CLEC_ESM_EVENTS_OUT_LEVEL_4                               (164U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V0_CLEC_ESM_EVENTS_OUT_LEVEL_5                               (165U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V0_CLEC_ESM_EVENTS_OUT_LEVEL_6                               (166U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V0_CLEC_ESM_EVENTS_OUT_LEVEL_7                               (167U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM0_MAIN_PLL_ECC_AGGR4_CORR_LEVEL_0                              (168U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM0_MAIN_PLL_ECC_AGGR4_UNCORR_LEVEL_0                            (169U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM0_MAIN_PLL_ECC_AGGR6_CORR_LEVEL_0                              (170U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM0_MAIN_PLL_ECC_AGGR6_UNCORR_LEVEL_0                            (171U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM0_PULSAR_PLL_ECC_AGGR8_CORR_LEVEL_0                            (172U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM0_PULSAR_PLL_ECC_AGGR8_UNCORR_LEVEL_0                          (173U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM0_PULSAR_PLL_ECC_AGGR10_CORR_LEVEL_0                           (174U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM0_PULSAR_PLL_ECC_AGGR10_UNCORR_LEVEL_0                         (175U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM1_MAIN_PLL_ECC_AGGR5_CORR_LEVEL_0                              (176U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM1_MAIN_PLL_ECC_AGGR5_UNCORR_LEVEL_0                            (177U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM1_MAIN_PLL_ECC_AGGR7_CORR_LEVEL_0                              (178U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM1_MAIN_PLL_ECC_AGGR7_UNCORR_LEVEL_0                            (179U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM1_PULSAR_PLL_ECC_AGGR9_CORR_LEVEL_0                            (180U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM1_PULSAR_PLL_ECC_AGGR9_UNCORR_LEVEL_0                          (181U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM1_PULSAR_PLL_ECC_AGGR11_CORR_LEVEL_0                           (182U)
#define CSLR_ESM0_ESM_LVL_EVENT_IDOM1_PULSAR_PLL_ECC_AGGR11_UNCORR_LEVEL_0                         (183U)
#define CSLR_ESM0_ESM_LVL_EVENT_MSRAM_1MB0_ECC_CORR_LEVEL_0                                        (184U)
#define CSLR_ESM0_ESM_LVL_EVENT_MSRAM_1MB0_ECC_UNCORR_LEVEL_0                                      (185U)
#define CSLR_ESM0_ESM_LVL_EVENT_MSRAM_1MB1_ECC_CORR_LEVEL_0                                        (186U)
#define CSLR_ESM0_ESM_LVL_EVENT_MSRAM_1MB1_ECC_UNCORR_LEVEL_0                                      (187U)
#define CSLR_ESM0_ESM_LVL_EVENT_MSRAM_1MB2_ECC_CORR_LEVEL_0                                        (188U)
#define CSLR_ESM0_ESM_LVL_EVENT_MSRAM_1MB2_ECC_UNCORR_LEVEL_0                                      (189U)
#define CSLR_ESM0_ESM_LVL_EVENT_MSRAM_1MB3_ECC_CORR_LEVEL_0                                        (190U)
#define CSLR_ESM0_ESM_LVL_EVENT_MSRAM_1MB3_ECC_UNCORR_LEVEL_0                                      (191U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V1_CLEC_ESM_EVENTS_OUT_LEVEL_0                               (192U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V1_CLEC_ESM_EVENTS_OUT_LEVEL_1                               (193U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V1_CLEC_ESM_EVENTS_OUT_LEVEL_2                               (194U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V1_CLEC_ESM_EVENTS_OUT_LEVEL_3                               (195U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V1_CLEC_ESM_EVENTS_OUT_LEVEL_4                               (196U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V1_CLEC_ESM_EVENTS_OUT_LEVEL_5                               (197U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V1_CLEC_ESM_EVENTS_OUT_LEVEL_6                               (198U)
#define CSLR_ESM0_ESM_LVL_EVENT_C7X256V1_CLEC_ESM_EVENTS_OUT_LEVEL_7                               (199U)
#define CSLR_ESM0_ESM_LVL_EVENT_PBIST3_DFT_PBIST_SAFETY_ERROR_0                                    (202U)
#define CSLR_ESM0_ESM_LVL_EVENT_PBIST4_DFT_PBIST_SAFETY_ERROR_0                                    (203U)
#define CSLR_ESM0_ESM_LVL_EVENT_PBIST5_DFT_PBIST_SAFETY_ERROR_0                                    (204U)
#define CSLR_ESM0_ESM_LVL_EVENT_PBIST6_DFT_PBIST_SAFETY_ERROR_0                                    (205U)
#define CSLR_ESM0_ESM_LVL_EVENT_PBIST7_DFT_PBIST_SAFETY_ERROR_0                                    (206U)
#define CSLR_ESM0_ESM_LVL_EVENT_PBIST8_DFT_PBIST_SAFETY_ERROR_0                                    (207U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS0_CORE0_ECC_AGGR_ECC_CORRECTED_LEVEL_0                        (208U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS0_CORE0_ECC_AGGR_ECC_UNCORRECTED_LEVEL_0                      (209U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS0_CORE0_EXP_INTR_0                                            (210U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS0_COMMON0_ECC_DE_TO_ESM_0_0                                   (211U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS0_COMMON0_ECC_SE_TO_ESM_0_0                                   (212U)
#define CSLR_ESM0_ESM_LVL_EVENT_PBIST1_DFT_PBIST_SAFETY_ERROR_0                                    (213U)
#define CSLR_ESM0_ESM_LVL_EVENT_PBIST2_DFT_PBIST_SAFETY_ERROR_0                                    (214U)
#define CSLR_ESM0_ESM_LVL_EVENT_MSRAM_1MB4_ECC_CORR_LEVEL_0                                        (215U)
#define CSLR_ESM0_ESM_LVL_EVENT_MSRAM_1MB4_ECC_UNCORR_LEVEL_0                                      (216U)
#define CSLR_ESM0_ESM_LVL_EVENT_MSRAM_1MB5_ECC_CORR_LEVEL_0                                        (217U)
#define CSLR_ESM0_ESM_LVL_EVENT_MSRAM_1MB5_ECC_UNCORR_LEVEL_0                                      (218U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS0_CORE1_ECC_AGGR_ECC_CORRECTED_LEVEL_0                        (219U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS0_CORE1_ECC_AGGR_ECC_UNCORRECTED_LEVEL_0                      (220U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS0_COMMON0_ECC_DE_TO_ESM_1_0                                   (221U)
#define CSLR_ESM0_ESM_LVL_EVENT_R5FSS0_COMMON0_ECC_SE_TO_ESM_1_0                                   (222U)
#define CSLR_ESM0_ESM_LVL_EVENT_DCC8_INTR_ERR_LEVEL_0                                              (223U)
#define CSLR_ESM0_ESM_PLS_EVENT0_RTI0_INTR_WWD_0                                                   (224U)
#define CSLR_ESM0_ESM_PLS_EVENT1_RTI0_INTR_WWD_0                                                   (224U)
#define CSLR_ESM0_ESM_PLS_EVENT2_RTI0_INTR_WWD_0                                                   (224U)
#define CSLR_ESM0_ESM_PLS_EVENT0_RTI1_INTR_WWD_0                                                   (225U)
#define CSLR_ESM0_ESM_PLS_EVENT1_RTI1_INTR_WWD_0                                                   (225U)
#define CSLR_ESM0_ESM_PLS_EVENT2_RTI1_INTR_WWD_0                                                   (225U)
#define CSLR_ESM0_ESM_PLS_EVENT0_C7X256V0_CLEC_DFT_PBIST_CPU_0                                     (226U)
#define CSLR_ESM0_ESM_PLS_EVENT1_C7X256V0_CLEC_DFT_PBIST_CPU_0                                     (226U)
#define CSLR_ESM0_ESM_PLS_EVENT2_C7X256V0_CLEC_DFT_PBIST_CPU_0                                     (226U)
#define CSLR_ESM0_ESM_PLS_EVENT0_WKUP_RTI0_INTR_WWD_0                                              (227U)
#define CSLR_ESM0_ESM_PLS_EVENT1_WKUP_RTI0_INTR_WWD_0                                              (227U)
#define CSLR_ESM0_ESM_PLS_EVENT2_WKUP_RTI0_INTR_WWD_0                                              (227U)
#define CSLR_ESM0_ESM_PLS_EVENT0_PBIST0_DFT_PBIST_CPU_0                                            (228U)
#define CSLR_ESM0_ESM_PLS_EVENT1_PBIST0_DFT_PBIST_CPU_0                                            (228U)
#define CSLR_ESM0_ESM_PLS_EVENT2_PBIST0_DFT_PBIST_CPU_0                                            (228U)
#define CSLR_ESM0_ESM_PLS_EVENT0_R5FSS0_COMMON0_BUS_MONITOR_ERR_PULSE_0                            (229U)
#define CSLR_ESM0_ESM_PLS_EVENT1_R5FSS0_COMMON0_BUS_MONITOR_ERR_PULSE_0                            (229U)
#define CSLR_ESM0_ESM_PLS_EVENT2_R5FSS0_COMMON0_BUS_MONITOR_ERR_PULSE_0                            (229U)
#define CSLR_ESM0_ESM_PLS_EVENT0_R5FSS0_CCM_COMPARE_STAT_PULSE_INTR_0                              (230U)
#define CSLR_ESM0_ESM_PLS_EVENT1_R5FSS0_CCM_COMPARE_STAT_PULSE_INTR_0                              (230U)
#define CSLR_ESM0_ESM_PLS_EVENT2_R5FSS0_CCM_COMPARE_STAT_PULSE_INTR_0                              (230U)
#define CSLR_ESM0_ESM_PLS_EVENT0_R5FSS0_COMMON0_COMPARE_ERR_PULSE_0                                (231U)
#define CSLR_ESM0_ESM_PLS_EVENT1_R5FSS0_COMMON0_COMPARE_ERR_PULSE_0                                (231U)
#define CSLR_ESM0_ESM_PLS_EVENT2_R5FSS0_COMMON0_COMPARE_ERR_PULSE_0                                (231U)
#define CSLR_ESM0_ESM_PLS_EVENT0_R5FSS0_COMMON0_SELFTEST_ERR_PULSE_0                               (232U)
#define CSLR_ESM0_ESM_PLS_EVENT1_R5FSS0_COMMON0_SELFTEST_ERR_PULSE_0                               (232U)
#define CSLR_ESM0_ESM_PLS_EVENT2_R5FSS0_COMMON0_SELFTEST_ERR_PULSE_0                               (232U)
#define CSLR_ESM0_ESM_PLS_EVENT0_R5FSS0_COMMON0_VIM_COMPARE_ERR_PULSE_0                            (233U)
#define CSLR_ESM0_ESM_PLS_EVENT1_R5FSS0_COMMON0_VIM_COMPARE_ERR_PULSE_0                            (233U)
#define CSLR_ESM0_ESM_PLS_EVENT2_R5FSS0_COMMON0_VIM_COMPARE_ERR_PULSE_0                            (233U)
#define CSLR_ESM0_ESM_PLS_EVENT0_WKUP_PBIST0_DFT_PBIST_CPU_0                                       (234U)
#define CSLR_ESM0_ESM_PLS_EVENT1_WKUP_PBIST0_DFT_PBIST_CPU_0                                       (234U)
#define CSLR_ESM0_ESM_PLS_EVENT2_WKUP_PBIST0_DFT_PBIST_CPU_0                                       (234U)
#define CSLR_ESM0_ESM_PLS_EVENT0_R5FSS1_COMMON0_BUS_MONITOR_ERR_PULSE_0                            (235U)
#define CSLR_ESM0_ESM_PLS_EVENT1_R5FSS1_COMMON0_BUS_MONITOR_ERR_PULSE_0                            (235U)
#define CSLR_ESM0_ESM_PLS_EVENT2_R5FSS1_COMMON0_BUS_MONITOR_ERR_PULSE_0                            (235U)
#define CSLR_ESM0_ESM_PLS_EVENT0_R5FSS1_CCM_COMPARE_STAT_PULSE_INTR_0                              (236U)
#define CSLR_ESM0_ESM_PLS_EVENT1_R5FSS1_CCM_COMPARE_STAT_PULSE_INTR_0                              (236U)
#define CSLR_ESM0_ESM_PLS_EVENT2_R5FSS1_CCM_COMPARE_STAT_PULSE_INTR_0                              (236U)
#define CSLR_ESM0_ESM_PLS_EVENT0_R5FSS1_COMMON0_COMPARE_ERR_PULSE_0                                (237U)
#define CSLR_ESM0_ESM_PLS_EVENT1_R5FSS1_COMMON0_COMPARE_ERR_PULSE_0                                (237U)
#define CSLR_ESM0_ESM_PLS_EVENT2_R5FSS1_COMMON0_COMPARE_ERR_PULSE_0                                (237U)
#define CSLR_ESM0_ESM_PLS_EVENT0_R5FSS1_COMMON0_SELFTEST_ERR_PULSE_0                               (238U)
#define CSLR_ESM0_ESM_PLS_EVENT1_R5FSS1_COMMON0_SELFTEST_ERR_PULSE_0                               (238U)
#define CSLR_ESM0_ESM_PLS_EVENT2_R5FSS1_COMMON0_SELFTEST_ERR_PULSE_0                               (238U)
#define CSLR_ESM0_ESM_PLS_EVENT0_R5FSS1_COMMON0_VIM_COMPARE_ERR_PULSE_0                            (239U)
#define CSLR_ESM0_ESM_PLS_EVENT1_R5FSS1_COMMON0_VIM_COMPARE_ERR_PULSE_0                            (239U)
#define CSLR_ESM0_ESM_PLS_EVENT2_R5FSS1_COMMON0_VIM_COMPARE_ERR_PULSE_0                            (239U)
#define CSLR_ESM0_ESM_PLS_EVENT0_WKUP_PBIST1_DFT_PBIST_CPU_0                                       (240U)
#define CSLR_ESM0_ESM_PLS_EVENT1_WKUP_PBIST1_DFT_PBIST_CPU_0                                       (240U)
#define CSLR_ESM0_ESM_PLS_EVENT2_WKUP_PBIST1_DFT_PBIST_CPU_0                                       (240U)
#define CSLR_ESM0_ESM_PLS_EVENT0_RTI2_INTR_WWD_0                                                   (241U)
#define CSLR_ESM0_ESM_PLS_EVENT1_RTI2_INTR_WWD_0                                                   (241U)
#define CSLR_ESM0_ESM_PLS_EVENT2_RTI2_INTR_WWD_0                                                   (241U)
#define CSLR_ESM0_ESM_PLS_EVENT0_RTI3_INTR_WWD_0                                                   (242U)
#define CSLR_ESM0_ESM_PLS_EVENT1_RTI3_INTR_WWD_0                                                   (242U)
#define CSLR_ESM0_ESM_PLS_EVENT2_RTI3_INTR_WWD_0                                                   (242U)
#define CSLR_ESM0_ESM_PLS_EVENT0_PBIST1_DFT_PBIST_CPU_0                                            (243U)
#define CSLR_ESM0_ESM_PLS_EVENT1_PBIST1_DFT_PBIST_CPU_0                                            (243U)
#define CSLR_ESM0_ESM_PLS_EVENT2_PBIST1_DFT_PBIST_CPU_0                                            (243U)
#define CSLR_ESM0_ESM_PLS_EVENT0_PBIST2_DFT_PBIST_CPU_0                                            (244U)
#define CSLR_ESM0_ESM_PLS_EVENT1_PBIST2_DFT_PBIST_CPU_0                                            (244U)
#define CSLR_ESM0_ESM_PLS_EVENT2_PBIST2_DFT_PBIST_CPU_0                                            (244U)
#define CSLR_ESM0_ESM_PLS_EVENT0_C7X256V1_CLEC_DFT_PBIST_CPU_0                                     (245U)
#define CSLR_ESM0_ESM_PLS_EVENT1_C7X256V1_CLEC_DFT_PBIST_CPU_0                                     (245U)
#define CSLR_ESM0_ESM_PLS_EVENT2_C7X256V1_CLEC_DFT_PBIST_CPU_0                                     (245U)
#define CSLR_ESM0_ESM_PLS_EVENT0_PBIST3_DFT_PBIST_CPU_0                                            (246U)
#define CSLR_ESM0_ESM_PLS_EVENT1_PBIST3_DFT_PBIST_CPU_0                                            (246U)
#define CSLR_ESM0_ESM_PLS_EVENT2_PBIST3_DFT_PBIST_CPU_0                                            (246U)
#define CSLR_ESM0_ESM_PLS_EVENT0_PBIST4_DFT_PBIST_CPU_0                                            (247U)
#define CSLR_ESM0_ESM_PLS_EVENT1_PBIST4_DFT_PBIST_CPU_0                                            (247U)
#define CSLR_ESM0_ESM_PLS_EVENT2_PBIST4_DFT_PBIST_CPU_0                                            (247U)
#define CSLR_ESM0_ESM_PLS_EVENT0_PBIST5_DFT_PBIST_CPU_0                                            (248U)
#define CSLR_ESM0_ESM_PLS_EVENT1_PBIST5_DFT_PBIST_CPU_0                                            (248U)
#define CSLR_ESM0_ESM_PLS_EVENT2_PBIST5_DFT_PBIST_CPU_0                                            (248U)
#define CSLR_ESM0_ESM_PLS_EVENT0_PBIST6_DFT_PBIST_CPU_0                                            (249U)
#define CSLR_ESM0_ESM_PLS_EVENT1_PBIST6_DFT_PBIST_CPU_0                                            (249U)
#define CSLR_ESM0_ESM_PLS_EVENT2_PBIST6_DFT_PBIST_CPU_0                                            (249U)
#define CSLR_ESM0_ESM_PLS_EVENT0_PBIST7_DFT_PBIST_CPU_0                                            (250U)
#define CSLR_ESM0_ESM_PLS_EVENT1_PBIST7_DFT_PBIST_CPU_0                                            (250U)
#define CSLR_ESM0_ESM_PLS_EVENT2_PBIST7_DFT_PBIST_CPU_0                                            (250U)
#define CSLR_ESM0_ESM_PLS_EVENT0_PBIST8_DFT_PBIST_CPU_0                                            (251U)
#define CSLR_ESM0_ESM_PLS_EVENT1_PBIST8_DFT_PBIST_CPU_0                                            (251U)
#define CSLR_ESM0_ESM_PLS_EVENT2_PBIST8_DFT_PBIST_CPU_0                                            (251U)
#define CSLR_ESM0_ESM_PLS_EVENT0_RTI4_INTR_WWD_0                                                   (252U)
#define CSLR_ESM0_ESM_PLS_EVENT1_RTI4_INTR_WWD_0                                                   (252U)
#define CSLR_ESM0_ESM_PLS_EVENT2_RTI4_INTR_WWD_0                                                   (252U)
#define CSLR_ESM0_ESM_PLS_EVENT0_RTI5_INTR_WWD_0                                                   (253U)
#define CSLR_ESM0_ESM_PLS_EVENT1_RTI5_INTR_WWD_0                                                   (253U)
#define CSLR_ESM0_ESM_PLS_EVENT2_RTI5_INTR_WWD_0                                                   (253U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_ESM0_INTERRUPT_MAP_H_ */

