// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tidl_quant_params.proto

#include "tidl_quant_params.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace tidl_quant_params {
PROTOBUF_CONSTEXPR TIDLNetQuantParams::TIDLNetQuantParams(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.layers_)*/{}
  , /*decltype(_impl_.num_layers_)*/0
  , /*decltype(_impl_.quant_type_)*/1
  , /*decltype(_impl_.calib_type_)*/1} {}
struct TIDLNetQuantParamsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TIDLNetQuantParamsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TIDLNetQuantParamsDefaultTypeInternal() {}
  union {
    TIDLNetQuantParams _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TIDLNetQuantParamsDefaultTypeInternal _TIDLNetQuantParams_default_instance_;
PROTOBUF_CONSTEXPR TidlLayerQuantParams::TidlLayerQuantParams(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.outputs_)*/{}
  , /*decltype(_impl_.weights_)*/{}
  , /*decltype(_impl_.bias_)*/{}
  , /*decltype(_impl_.slope_)*/{}
  , /*decltype(_impl_.layer_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.layer_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.layer_index_)*/0u
  , /*decltype(_impl_.bit_depth_)*/8u} {}
struct TidlLayerQuantParamsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TidlLayerQuantParamsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TidlLayerQuantParamsDefaultTypeInternal() {}
  union {
    TidlLayerQuantParams _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TidlLayerQuantParamsDefaultTypeInternal _TidlLayerQuantParams_default_instance_;
PROTOBUF_CONSTEXPR TidlTensorQuantParams::TidlTensorQuantParams(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.scale_)*/{}
  , /*decltype(_impl_.zero_point_)*/{}
  , /*decltype(_impl_._zero_point_cached_byte_size_)*/{0}
  , /*decltype(_impl_.value_)*/{}
  , /*decltype(_impl_.element_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.is_symmetric_)*/false
  , /*decltype(_impl_.size_)*/0u
  , /*decltype(_impl_.min_)*/-3.40282347e+38f
  , /*decltype(_impl_.max_)*/3.40282347e+38f} {}
struct TidlTensorQuantParamsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TidlTensorQuantParamsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TidlTensorQuantParamsDefaultTypeInternal() {}
  union {
    TidlTensorQuantParams _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TidlTensorQuantParamsDefaultTypeInternal _TidlTensorQuantParams_default_instance_;
}  // namespace tidl_quant_params
static ::_pb::Metadata file_level_metadata_tidl_5fquant_5fparams_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_tidl_5fquant_5fparams_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_tidl_5fquant_5fparams_2eproto = nullptr;

const uint32_t TableStruct_tidl_5fquant_5fparams_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TIDLNetQuantParams, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TIDLNetQuantParams, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TIDLNetQuantParams, _impl_.num_layers_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TIDLNetQuantParams, _impl_.quant_type_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TIDLNetQuantParams, _impl_.calib_type_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TIDLNetQuantParams, _impl_.layers_),
  0,
  1,
  2,
  ~0u,
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlLayerQuantParams, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlLayerQuantParams, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlLayerQuantParams, _impl_.layer_index_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlLayerQuantParams, _impl_.layer_name_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlLayerQuantParams, _impl_.layer_type_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlLayerQuantParams, _impl_.bit_depth_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlLayerQuantParams, _impl_.outputs_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlLayerQuantParams, _impl_.weights_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlLayerQuantParams, _impl_.bias_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlLayerQuantParams, _impl_.slope_),
  2,
  0,
  1,
  3,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlTensorQuantParams, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlTensorQuantParams, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlTensorQuantParams, _impl_.is_symmetric_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlTensorQuantParams, _impl_.min_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlTensorQuantParams, _impl_.max_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlTensorQuantParams, _impl_.size_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlTensorQuantParams, _impl_.element_type_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlTensorQuantParams, _impl_.scale_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlTensorQuantParams, _impl_.zero_point_),
  PROTOBUF_FIELD_OFFSET(::tidl_quant_params::TidlTensorQuantParams, _impl_.value_),
  1,
  3,
  4,
  2,
  0,
  ~0u,
  ~0u,
  ~0u,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, -1, sizeof(::tidl_quant_params::TIDLNetQuantParams)},
  { 14, 28, -1, sizeof(::tidl_quant_params::TidlLayerQuantParams)},
  { 36, 50, -1, sizeof(::tidl_quant_params::TidlTensorQuantParams)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::tidl_quant_params::_TIDLNetQuantParams_default_instance_._instance,
  &::tidl_quant_params::_TidlLayerQuantParams_default_instance_._instance,
  &::tidl_quant_params::_TidlTensorQuantParams_default_instance_._instance,
};

const char descriptor_table_protodef_tidl_5fquant_5fparams_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027tidl_quant_params.proto\022\021tidl_quant_pa"
  "rams\"\343\001\n\022TIDLNetQuantParams\022\022\n\nnum_layer"
  "s\030\001 \001(\005\022\?\n\nquant_type\030\002 \001(\0162 .tidl_quant"
  "_params.TidlQuantType:\tSYMMETRIC\022\?\n\ncali"
  "b_type\030\003 \001(\0162 .tidl_quant_params.TidlCal"
  "ibType:\tPERTENSOR\0227\n\006layers\030\004 \003(\0132\'.tidl"
  "_quant_params.TidlLayerQuantParams\"\320\002\n\024T"
  "idlLayerQuantParams\022\023\n\013layer_index\030\001 \001(\r"
  "\022\022\n\nlayer_name\030\002 \001(\t\022\022\n\nlayer_type\030\003 \001(\t"
  "\022\024\n\tbit_depth\030\004 \001(\r:\0018\0229\n\007outputs\030\006 \003(\0132"
  "(.tidl_quant_params.TidlTensorQuantParam"
  "s\0229\n\007weights\030\007 \003(\0132(.tidl_quant_params.T"
  "idlTensorQuantParams\0226\n\004bias\030\010 \003(\0132(.tid"
  "l_quant_params.TidlTensorQuantParams\0227\n\005"
  "slope\030\t \003(\0132(.tidl_quant_params.TidlTens"
  "orQuantParams\"\321\001\n\025TidlTensorQuantParams\022"
  "\033\n\014is_symmetric\030\001 \001(\010:\005false\022\034\n\003min\030\002 \001("
  "\002:\017-3.40282347e+38\022\033\n\003max\030\003 \001(\002:\0163.40282"
  "347e+38\022\014\n\004size\030\004 \001(\r\022\024\n\014element_type\030\005 "
  "\001(\t\022\021\n\005scale\030\006 \003(\001B\002\020\001\022\026\n\nzero_point\030\007 \003"
  "(\005B\002\020\001\022\021\n\005value\030\010 \003(\001B\002\020\001*.\n\rTidlQuantTy"
  "pe\022\r\n\tSYMMETRIC\020\001\022\016\n\nASYMMETRIC\020\002*.\n\rTid"
  "lCalibType\022\r\n\tPERTENSOR\020\001\022\016\n\nPERCHANNEL\020"
  "\002"
  ;
static ::_pbi::once_flag descriptor_table_tidl_5fquant_5fparams_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_tidl_5fquant_5fparams_2eproto = {
    false, false, 921, descriptor_table_protodef_tidl_5fquant_5fparams_2eproto,
    "tidl_quant_params.proto",
    &descriptor_table_tidl_5fquant_5fparams_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_tidl_5fquant_5fparams_2eproto::offsets,
    file_level_metadata_tidl_5fquant_5fparams_2eproto, file_level_enum_descriptors_tidl_5fquant_5fparams_2eproto,
    file_level_service_descriptors_tidl_5fquant_5fparams_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_tidl_5fquant_5fparams_2eproto_getter() {
  return &descriptor_table_tidl_5fquant_5fparams_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_tidl_5fquant_5fparams_2eproto(&descriptor_table_tidl_5fquant_5fparams_2eproto);
namespace tidl_quant_params {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TidlQuantType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_tidl_5fquant_5fparams_2eproto);
  return file_level_enum_descriptors_tidl_5fquant_5fparams_2eproto[0];
}
bool TidlQuantType_IsValid(int value) {
  switch (value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TidlCalibType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_tidl_5fquant_5fparams_2eproto);
  return file_level_enum_descriptors_tidl_5fquant_5fparams_2eproto[1];
}
bool TidlCalibType_IsValid(int value) {
  switch (value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class TIDLNetQuantParams::_Internal {
 public:
  using HasBits = decltype(std::declval<TIDLNetQuantParams>()._impl_._has_bits_);
  static void set_has_num_layers(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_quant_type(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_calib_type(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

TIDLNetQuantParams::TIDLNetQuantParams(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tidl_quant_params.TIDLNetQuantParams)
}
TIDLNetQuantParams::TIDLNetQuantParams(const TIDLNetQuantParams& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TIDLNetQuantParams* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.layers_){from._impl_.layers_}
    , decltype(_impl_.num_layers_){}
    , decltype(_impl_.quant_type_){}
    , decltype(_impl_.calib_type_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.num_layers_, &from._impl_.num_layers_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.calib_type_) -
    reinterpret_cast<char*>(&_impl_.num_layers_)) + sizeof(_impl_.calib_type_));
  // @@protoc_insertion_point(copy_constructor:tidl_quant_params.TIDLNetQuantParams)
}

inline void TIDLNetQuantParams::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.layers_){arena}
    , decltype(_impl_.num_layers_){0}
    , decltype(_impl_.quant_type_){1}
    , decltype(_impl_.calib_type_){1}
  };
}

TIDLNetQuantParams::~TIDLNetQuantParams() {
  // @@protoc_insertion_point(destructor:tidl_quant_params.TIDLNetQuantParams)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TIDLNetQuantParams::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.layers_.~RepeatedPtrField();
}

void TIDLNetQuantParams::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TIDLNetQuantParams::Clear() {
// @@protoc_insertion_point(message_clear_start:tidl_quant_params.TIDLNetQuantParams)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.layers_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    _impl_.num_layers_ = 0;
    _impl_.quant_type_ = 1;
    _impl_.calib_type_ = 1;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TIDLNetQuantParams::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 num_layers = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_num_layers(&has_bits);
          _impl_.num_layers_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .tidl_quant_params.TidlQuantType quant_type = 2 [default = SYMMETRIC];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::tidl_quant_params::TidlQuantType_IsValid(val))) {
            _internal_set_quant_type(static_cast<::tidl_quant_params::TidlQuantType>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(2, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // optional .tidl_quant_params.TidlCalibType calib_type = 3 [default = PERTENSOR];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::tidl_quant_params::TidlCalibType_IsValid(val))) {
            _internal_set_calib_type(static_cast<::tidl_quant_params::TidlCalibType>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(3, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // repeated .tidl_quant_params.TidlLayerQuantParams layers = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_layers(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TIDLNetQuantParams::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tidl_quant_params.TIDLNetQuantParams)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 num_layers = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_num_layers(), target);
  }

  // optional .tidl_quant_params.TidlQuantType quant_type = 2 [default = SYMMETRIC];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_quant_type(), target);
  }

  // optional .tidl_quant_params.TidlCalibType calib_type = 3 [default = PERTENSOR];
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_calib_type(), target);
  }

  // repeated .tidl_quant_params.TidlLayerQuantParams layers = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_layers_size()); i < n; i++) {
    const auto& repfield = this->_internal_layers(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tidl_quant_params.TIDLNetQuantParams)
  return target;
}

size_t TIDLNetQuantParams::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tidl_quant_params.TIDLNetQuantParams)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .tidl_quant_params.TidlLayerQuantParams layers = 4;
  total_size += 1UL * this->_internal_layers_size();
  for (const auto& msg : this->_impl_.layers_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional int32 num_layers = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_num_layers());
    }

    // optional .tidl_quant_params.TidlQuantType quant_type = 2 [default = SYMMETRIC];
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_quant_type());
    }

    // optional .tidl_quant_params.TidlCalibType calib_type = 3 [default = PERTENSOR];
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_calib_type());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TIDLNetQuantParams::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TIDLNetQuantParams::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TIDLNetQuantParams::GetClassData() const { return &_class_data_; }


void TIDLNetQuantParams::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TIDLNetQuantParams*>(&to_msg);
  auto& from = static_cast<const TIDLNetQuantParams&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tidl_quant_params.TIDLNetQuantParams)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.layers_.MergeFrom(from._impl_.layers_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.num_layers_ = from._impl_.num_layers_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.quant_type_ = from._impl_.quant_type_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.calib_type_ = from._impl_.calib_type_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TIDLNetQuantParams::CopyFrom(const TIDLNetQuantParams& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tidl_quant_params.TIDLNetQuantParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TIDLNetQuantParams::IsInitialized() const {
  return true;
}

void TIDLNetQuantParams::InternalSwap(TIDLNetQuantParams* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.layers_.InternalSwap(&other->_impl_.layers_);
  swap(_impl_.num_layers_, other->_impl_.num_layers_);
  swap(_impl_.quant_type_, other->_impl_.quant_type_);
  swap(_impl_.calib_type_, other->_impl_.calib_type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TIDLNetQuantParams::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tidl_5fquant_5fparams_2eproto_getter, &descriptor_table_tidl_5fquant_5fparams_2eproto_once,
      file_level_metadata_tidl_5fquant_5fparams_2eproto[0]);
}

// ===================================================================

class TidlLayerQuantParams::_Internal {
 public:
  using HasBits = decltype(std::declval<TidlLayerQuantParams>()._impl_._has_bits_);
  static void set_has_layer_index(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_layer_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_layer_type(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_bit_depth(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

TidlLayerQuantParams::TidlLayerQuantParams(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tidl_quant_params.TidlLayerQuantParams)
}
TidlLayerQuantParams::TidlLayerQuantParams(const TidlLayerQuantParams& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TidlLayerQuantParams* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.outputs_){from._impl_.outputs_}
    , decltype(_impl_.weights_){from._impl_.weights_}
    , decltype(_impl_.bias_){from._impl_.bias_}
    , decltype(_impl_.slope_){from._impl_.slope_}
    , decltype(_impl_.layer_name_){}
    , decltype(_impl_.layer_type_){}
    , decltype(_impl_.layer_index_){}
    , decltype(_impl_.bit_depth_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.layer_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.layer_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_layer_name()) {
    _this->_impl_.layer_name_.Set(from._internal_layer_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.layer_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.layer_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_layer_type()) {
    _this->_impl_.layer_type_.Set(from._internal_layer_type(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.layer_index_, &from._impl_.layer_index_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.bit_depth_) -
    reinterpret_cast<char*>(&_impl_.layer_index_)) + sizeof(_impl_.bit_depth_));
  // @@protoc_insertion_point(copy_constructor:tidl_quant_params.TidlLayerQuantParams)
}

inline void TidlLayerQuantParams::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.outputs_){arena}
    , decltype(_impl_.weights_){arena}
    , decltype(_impl_.bias_){arena}
    , decltype(_impl_.slope_){arena}
    , decltype(_impl_.layer_name_){}
    , decltype(_impl_.layer_type_){}
    , decltype(_impl_.layer_index_){0u}
    , decltype(_impl_.bit_depth_){8u}
  };
  _impl_.layer_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.layer_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.layer_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.layer_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TidlLayerQuantParams::~TidlLayerQuantParams() {
  // @@protoc_insertion_point(destructor:tidl_quant_params.TidlLayerQuantParams)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TidlLayerQuantParams::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.outputs_.~RepeatedPtrField();
  _impl_.weights_.~RepeatedPtrField();
  _impl_.bias_.~RepeatedPtrField();
  _impl_.slope_.~RepeatedPtrField();
  _impl_.layer_name_.Destroy();
  _impl_.layer_type_.Destroy();
}

void TidlLayerQuantParams::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TidlLayerQuantParams::Clear() {
// @@protoc_insertion_point(message_clear_start:tidl_quant_params.TidlLayerQuantParams)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.outputs_.Clear();
  _impl_.weights_.Clear();
  _impl_.bias_.Clear();
  _impl_.slope_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.layer_name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.layer_type_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x0000000cu) {
    _impl_.layer_index_ = 0u;
    _impl_.bit_depth_ = 8u;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TidlLayerQuantParams::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 layer_index = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_layer_index(&has_bits);
          _impl_.layer_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string layer_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_layer_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "tidl_quant_params.TidlLayerQuantParams.layer_name");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional string layer_type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_layer_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "tidl_quant_params.TidlLayerQuantParams.layer_type");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional uint32 bit_depth = 4 [default = 8];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_bit_depth(&has_bits);
          _impl_.bit_depth_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .tidl_quant_params.TidlTensorQuantParams outputs = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_outputs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .tidl_quant_params.TidlTensorQuantParams weights = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_weights(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .tidl_quant_params.TidlTensorQuantParams bias = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_bias(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<66>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .tidl_quant_params.TidlTensorQuantParams slope = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_slope(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<74>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TidlLayerQuantParams::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tidl_quant_params.TidlLayerQuantParams)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 layer_index = 1;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_layer_index(), target);
  }

  // optional string layer_name = 2;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_layer_name().data(), static_cast<int>(this->_internal_layer_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "tidl_quant_params.TidlLayerQuantParams.layer_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_layer_name(), target);
  }

  // optional string layer_type = 3;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_layer_type().data(), static_cast<int>(this->_internal_layer_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "tidl_quant_params.TidlLayerQuantParams.layer_type");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_layer_type(), target);
  }

  // optional uint32 bit_depth = 4 [default = 8];
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_bit_depth(), target);
  }

  // repeated .tidl_quant_params.TidlTensorQuantParams outputs = 6;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_outputs_size()); i < n; i++) {
    const auto& repfield = this->_internal_outputs(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(6, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .tidl_quant_params.TidlTensorQuantParams weights = 7;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_weights_size()); i < n; i++) {
    const auto& repfield = this->_internal_weights(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(7, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .tidl_quant_params.TidlTensorQuantParams bias = 8;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_bias_size()); i < n; i++) {
    const auto& repfield = this->_internal_bias(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(8, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .tidl_quant_params.TidlTensorQuantParams slope = 9;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_slope_size()); i < n; i++) {
    const auto& repfield = this->_internal_slope(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(9, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tidl_quant_params.TidlLayerQuantParams)
  return target;
}

size_t TidlLayerQuantParams::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tidl_quant_params.TidlLayerQuantParams)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .tidl_quant_params.TidlTensorQuantParams outputs = 6;
  total_size += 1UL * this->_internal_outputs_size();
  for (const auto& msg : this->_impl_.outputs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .tidl_quant_params.TidlTensorQuantParams weights = 7;
  total_size += 1UL * this->_internal_weights_size();
  for (const auto& msg : this->_impl_.weights_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .tidl_quant_params.TidlTensorQuantParams bias = 8;
  total_size += 1UL * this->_internal_bias_size();
  for (const auto& msg : this->_impl_.bias_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .tidl_quant_params.TidlTensorQuantParams slope = 9;
  total_size += 1UL * this->_internal_slope_size();
  for (const auto& msg : this->_impl_.slope_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional string layer_name = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_layer_name());
    }

    // optional string layer_type = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_layer_type());
    }

    // optional uint32 layer_index = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_layer_index());
    }

    // optional uint32 bit_depth = 4 [default = 8];
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_bit_depth());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TidlLayerQuantParams::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TidlLayerQuantParams::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TidlLayerQuantParams::GetClassData() const { return &_class_data_; }


void TidlLayerQuantParams::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TidlLayerQuantParams*>(&to_msg);
  auto& from = static_cast<const TidlLayerQuantParams&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tidl_quant_params.TidlLayerQuantParams)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.outputs_.MergeFrom(from._impl_.outputs_);
  _this->_impl_.weights_.MergeFrom(from._impl_.weights_);
  _this->_impl_.bias_.MergeFrom(from._impl_.bias_);
  _this->_impl_.slope_.MergeFrom(from._impl_.slope_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_layer_name(from._internal_layer_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_layer_type(from._internal_layer_type());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.layer_index_ = from._impl_.layer_index_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.bit_depth_ = from._impl_.bit_depth_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TidlLayerQuantParams::CopyFrom(const TidlLayerQuantParams& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tidl_quant_params.TidlLayerQuantParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TidlLayerQuantParams::IsInitialized() const {
  return true;
}

void TidlLayerQuantParams::InternalSwap(TidlLayerQuantParams* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.outputs_.InternalSwap(&other->_impl_.outputs_);
  _impl_.weights_.InternalSwap(&other->_impl_.weights_);
  _impl_.bias_.InternalSwap(&other->_impl_.bias_);
  _impl_.slope_.InternalSwap(&other->_impl_.slope_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.layer_name_, lhs_arena,
      &other->_impl_.layer_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.layer_type_, lhs_arena,
      &other->_impl_.layer_type_, rhs_arena
  );
  swap(_impl_.layer_index_, other->_impl_.layer_index_);
  swap(_impl_.bit_depth_, other->_impl_.bit_depth_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TidlLayerQuantParams::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tidl_5fquant_5fparams_2eproto_getter, &descriptor_table_tidl_5fquant_5fparams_2eproto_once,
      file_level_metadata_tidl_5fquant_5fparams_2eproto[1]);
}

// ===================================================================

class TidlTensorQuantParams::_Internal {
 public:
  using HasBits = decltype(std::declval<TidlTensorQuantParams>()._impl_._has_bits_);
  static void set_has_is_symmetric(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_min(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_max(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_size(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_element_type(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

TidlTensorQuantParams::TidlTensorQuantParams(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tidl_quant_params.TidlTensorQuantParams)
}
TidlTensorQuantParams::TidlTensorQuantParams(const TidlTensorQuantParams& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TidlTensorQuantParams* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.scale_){from._impl_.scale_}
    , decltype(_impl_.zero_point_){from._impl_.zero_point_}
    , /*decltype(_impl_._zero_point_cached_byte_size_)*/{0}
    , decltype(_impl_.value_){from._impl_.value_}
    , decltype(_impl_.element_type_){}
    , decltype(_impl_.is_symmetric_){}
    , decltype(_impl_.size_){}
    , decltype(_impl_.min_){}
    , decltype(_impl_.max_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.element_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.element_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_element_type()) {
    _this->_impl_.element_type_.Set(from._internal_element_type(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.is_symmetric_, &from._impl_.is_symmetric_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.max_) -
    reinterpret_cast<char*>(&_impl_.is_symmetric_)) + sizeof(_impl_.max_));
  // @@protoc_insertion_point(copy_constructor:tidl_quant_params.TidlTensorQuantParams)
}

inline void TidlTensorQuantParams::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.scale_){arena}
    , decltype(_impl_.zero_point_){arena}
    , /*decltype(_impl_._zero_point_cached_byte_size_)*/{0}
    , decltype(_impl_.value_){arena}
    , decltype(_impl_.element_type_){}
    , decltype(_impl_.is_symmetric_){false}
    , decltype(_impl_.size_){0u}
    , decltype(_impl_.min_){-3.40282347e+38f}
    , decltype(_impl_.max_){3.40282347e+38f}
  };
  _impl_.element_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.element_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TidlTensorQuantParams::~TidlTensorQuantParams() {
  // @@protoc_insertion_point(destructor:tidl_quant_params.TidlTensorQuantParams)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TidlTensorQuantParams::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.scale_.~RepeatedField();
  _impl_.zero_point_.~RepeatedField();
  _impl_.value_.~RepeatedField();
  _impl_.element_type_.Destroy();
}

void TidlTensorQuantParams::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TidlTensorQuantParams::Clear() {
// @@protoc_insertion_point(message_clear_start:tidl_quant_params.TidlTensorQuantParams)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.scale_.Clear();
  _impl_.zero_point_.Clear();
  _impl_.value_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.element_type_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x0000001eu) {
    ::memset(&_impl_.is_symmetric_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.size_) -
        reinterpret_cast<char*>(&_impl_.is_symmetric_)) + sizeof(_impl_.size_));
    _impl_.min_ = -3.40282347e+38f;
    _impl_.max_ = 3.40282347e+38f;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TidlTensorQuantParams::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional bool is_symmetric = 1 [default = false];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_is_symmetric(&has_bits);
          _impl_.is_symmetric_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional float min = 2 [default = -3.40282347e+38];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _Internal::set_has_min(&has_bits);
          _impl_.min_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // optional float max = 3 [default = 3.40282347e+38];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _Internal::set_has_max(&has_bits);
          _impl_.max_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 size = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_size(&has_bits);
          _impl_.size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string element_type = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_element_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "tidl_quant_params.TidlTensorQuantParams.element_type");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // repeated double scale = 6 [packed = true];
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_scale(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 49) {
          _internal_add_scale(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 zero_point = 7 [packed = true];
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_zero_point(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 56) {
          _internal_add_zero_point(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated double value = 8 [packed = true];
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_value(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 65) {
          _internal_add_value(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TidlTensorQuantParams::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tidl_quant_params.TidlTensorQuantParams)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional bool is_symmetric = 1 [default = false];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_is_symmetric(), target);
  }

  // optional float min = 2 [default = -3.40282347e+38];
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_min(), target);
  }

  // optional float max = 3 [default = 3.40282347e+38];
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_max(), target);
  }

  // optional uint32 size = 4;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_size(), target);
  }

  // optional string element_type = 5;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_element_type().data(), static_cast<int>(this->_internal_element_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "tidl_quant_params.TidlTensorQuantParams.element_type");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_element_type(), target);
  }

  // repeated double scale = 6 [packed = true];
  if (this->_internal_scale_size() > 0) {
    target = stream->WriteFixedPacked(6, _internal_scale(), target);
  }

  // repeated int32 zero_point = 7 [packed = true];
  {
    int byte_size = _impl_._zero_point_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          7, _internal_zero_point(), byte_size, target);
    }
  }

  // repeated double value = 8 [packed = true];
  if (this->_internal_value_size() > 0) {
    target = stream->WriteFixedPacked(8, _internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tidl_quant_params.TidlTensorQuantParams)
  return target;
}

size_t TidlTensorQuantParams::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tidl_quant_params.TidlTensorQuantParams)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double scale = 6 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_scale_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated int32 zero_point = 7 [packed = true];
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.zero_point_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._zero_point_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated double value = 8 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_value_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // optional string element_type = 5;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_element_type());
    }

    // optional bool is_symmetric = 1 [default = false];
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

    // optional uint32 size = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_size());
    }

    // optional float min = 2 [default = -3.40282347e+38];
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 4;
    }

    // optional float max = 3 [default = 3.40282347e+38];
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 4;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TidlTensorQuantParams::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TidlTensorQuantParams::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TidlTensorQuantParams::GetClassData() const { return &_class_data_; }


void TidlTensorQuantParams::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TidlTensorQuantParams*>(&to_msg);
  auto& from = static_cast<const TidlTensorQuantParams&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tidl_quant_params.TidlTensorQuantParams)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.scale_.MergeFrom(from._impl_.scale_);
  _this->_impl_.zero_point_.MergeFrom(from._impl_.zero_point_);
  _this->_impl_.value_.MergeFrom(from._impl_.value_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_element_type(from._internal_element_type());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.is_symmetric_ = from._impl_.is_symmetric_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.size_ = from._impl_.size_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.min_ = from._impl_.min_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.max_ = from._impl_.max_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TidlTensorQuantParams::CopyFrom(const TidlTensorQuantParams& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tidl_quant_params.TidlTensorQuantParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TidlTensorQuantParams::IsInitialized() const {
  return true;
}

void TidlTensorQuantParams::InternalSwap(TidlTensorQuantParams* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.scale_.InternalSwap(&other->_impl_.scale_);
  _impl_.zero_point_.InternalSwap(&other->_impl_.zero_point_);
  _impl_.value_.InternalSwap(&other->_impl_.value_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.element_type_, lhs_arena,
      &other->_impl_.element_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TidlTensorQuantParams, _impl_.size_)
      + sizeof(TidlTensorQuantParams::_impl_.size_)
      - PROTOBUF_FIELD_OFFSET(TidlTensorQuantParams, _impl_.is_symmetric_)>(
          reinterpret_cast<char*>(&_impl_.is_symmetric_),
          reinterpret_cast<char*>(&other->_impl_.is_symmetric_));
  swap(_impl_.min_, other->_impl_.min_);
  swap(_impl_.max_, other->_impl_.max_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TidlTensorQuantParams::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tidl_5fquant_5fparams_2eproto_getter, &descriptor_table_tidl_5fquant_5fparams_2eproto_once,
      file_level_metadata_tidl_5fquant_5fparams_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace tidl_quant_params
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tidl_quant_params::TIDLNetQuantParams*
Arena::CreateMaybeMessage< ::tidl_quant_params::TIDLNetQuantParams >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tidl_quant_params::TIDLNetQuantParams >(arena);
}
template<> PROTOBUF_NOINLINE ::tidl_quant_params::TidlLayerQuantParams*
Arena::CreateMaybeMessage< ::tidl_quant_params::TidlLayerQuantParams >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tidl_quant_params::TidlLayerQuantParams >(arena);
}
template<> PROTOBUF_NOINLINE ::tidl_quant_params::TidlTensorQuantParams*
Arena::CreateMaybeMessage< ::tidl_quant_params::TidlTensorQuantParams >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tidl_quant_params::TidlTensorQuantParams >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
