"""
    DCC XML Generator Functions
    
    AWB
"""

import os
import dcc
import dccxml
import utils
from utils import g_tuning_output
import numpy as np

def get_data(ref_names, img_width, img_height, color_pattern, xp, yp, blk_pre, blk_post):

    pos = []
    rgb = []
    yuv = []

    for ref in ref_names:
        cc_pos, cc_mean = utils.sample_cc(ref, img_width, img_height, color_pattern, xp, yp, blk_pre, blk_post, 0)
        cc_yuv = utils.rgb_to_normalized_uv(cc_mean[:,0], cc_mean[:,1], cc_mean[:,2])

        pos.append(cc_pos)
        rgb.append(cc_mean)
        yuv.append(cc_yuv)

    return (pos, rgb, yuv)

def gen_calib(in_colortemp, rgb, yuv):
    num_of_lightbox_ref     = len(in_colortemp)
    num_of_gray             = 4
    radius2                 = 50
    bid                     = 2

    in_Cb = np.zeros((num_of_lightbox_ref, 4))
    in_Cr = np.zeros((num_of_lightbox_ref, 4))
    in_R = np.zeros((num_of_lightbox_ref, 4))
    in_G = np.zeros((num_of_lightbox_ref, 4))
    in_B = np.zeros((num_of_lightbox_ref, 4))
    for k in range(num_of_lightbox_ref):
        in_Cb[k, :] = yuv[k][18+1:18+5, 1]
        in_Cr[k, :] = yuv[k][18+1:18+5, 2]
        in_R[k, :]  = rgb[k][18+1:18+5, 0]
        in_G[k, :]  = rgb[k][18+1:18+5, 1]
        in_B[k, :]  = rgb[k][18+1:18+5, 2]

        b = np.ceil(np.log2(in_G[k, :].max()))
        if b > 10:
            in_R[k,:] = in_R[k,:] / 2**(b-10)
            in_G[k,:] = in_G[k,:] / 2**(b-10)
            in_B[k,:] = in_B[k,:] / 2**(b-10)

    # Interpolate references                                               %
    num_of_interp = np.zeros(num_of_lightbox_ref-1) 
    for i in range(num_of_lightbox_ref-1):
        sqdis = (in_Cb[i, bid] - in_Cb[i+1, bid])**2 + (in_Cr[i, bid] - in_Cr[i+1, bid])**2
        num_of_interp[i]= max(0, np.round(np.sqrt(sqdis/radius2)) - 1)

    num_of_ref_v2242 = int(num_of_lightbox_ref + sum(num_of_interp))

    # Interpolate Color Temp
    out_colortemp = np.zeros( (1,num_of_ref_v2242) )
    x = np.arange(num_of_ref_v2242)
    yp = in_colortemp 
    xp = list(range(len(in_colortemp)))
    for i in range(1, len(xp)):
        xp[i] = xp[i-1] + num_of_interp[i-1] + 1
    out_colortemp = np.around(np.interp(x, xp, yp))

    # Recommend using quadratic fit
    out_Cb = np.zeros( (num_of_ref_v2242, num_of_gray) )
    out_Cr = np.zeros( (num_of_ref_v2242, num_of_gray) )

    for i in range(num_of_gray):
        P = np.polyfit(in_Cr[:,i], in_Cb[:,i], 2)
        fCr = np.interp(x, xp, in_Cr[:,i])
        fCb = np.polyval(P, fCr)
        out_Cr[:, i] = fCr
        out_Cb[:, i] = fCb

    # Linearly interpolate R, G, B independently
    out_R = np.zeros( (num_of_ref_v2242, num_of_gray) )
    out_G = np.zeros( (num_of_ref_v2242, num_of_gray) )
    out_B = np.zeros( (num_of_ref_v2242, num_of_gray) )

    for i in range(num_of_gray):
        out_R[:, i] = np.interp(x, xp, in_R[:,i])
        out_G[:, i] = np.interp(x, xp, in_G[:,i])
        out_B[:, i] = np.interp(x, xp, in_B[:,i])

    if 0:
        import matplotlib.pyplot as plt
        plt.figure()
        for j in range(4):
            plt.plot(out_Cr[:, j], out_Cb[:, j], '.-')
            plt.plot(in_Cr[:, j], in_Cb[:, j], 'o')
        plt.show()

    OUTPUT = {}
    OUTPUT['num_of_ref_1'] = num_of_ref_v2242
    OUTPUT['num_of_ref_2'] = num_of_lightbox_ref
    OUTPUT['num_of_gray']  = num_of_gray
    OUTPUT['Cb_1']         = out_Cb.astype(np.int16)
    OUTPUT['Cr_1']         = out_Cr.astype(np.int16)
    OUTPUT['R_1']          = out_R.astype(np.int16)
    OUTPUT['G_1']          = out_G.astype(np.int16)
    OUTPUT['B_1']          = out_B.astype(np.int16)
    OUTPUT['colortemp_1']  = out_colortemp.astype(np.int16)

    OUTPUT['ref_index_2']  = np.array(xp, dtype=np.int16)
    OUTPUT['Cb_2']         = in_Cb.astype(np.int16)
    OUTPUT['Cr_2']         = in_Cr.astype(np.int16)
    OUTPUT['R_2']          = in_R.astype(np.int16)
    OUTPUT['G_2']          = in_G.astype(np.int16)
    OUTPUT['B_2']          = in_B.astype(np.int16)
    OUTPUT['colortemp_2']  = np.array(in_colortemp, dtype=np.int16)

    return OUTPUT

def GenAWBParams(handle, AWB_params, cls_id):
    return

def GenAWBXML(directory, filebase, params, AWB_params):

    output = {}
    if 'RAW_RGB2RGB' in params:
        L = len(params['RAW_RGB2RGB']) if isinstance(params['RAW_RGB2RGB'], dict) else 1
        if L >= 4:
            calib = 1
            ref_names       = [params['RAW_RGB2RGB'][k][0] for k in range(L)]
            color_temps     = [params['RAW_RGB2RGB'][k][1] for k in range(L)]
            img_width       = params['SENSOR_WIDTH']
            img_height      = params['SENSOR_HEIGHT']
            color_pattern   = params['COLOR_PATTERN']

            xp, yp = [], []
            if params['WDR_MODE'] == 'wdr':
                xp = utils.get_wdr_knee_points(params['WDR_KNEE_X'])
                yp = utils.get_wdr_knee_points(params['WDR_KNEE_Y'])
                blk_pre = g_tuning_output.get('wdr_black_pre', 0)
                blk_post = g_tuning_output.get('wdr_black_post', 0)
            else: # linear mode
                blk_pre = 0
                blk_post = g_tuning_output.get('linear_black_level', 0)

            _, rgb, yuv = get_data(ref_names, img_width, img_height, color_pattern, xp, yp, blk_pre, blk_post)
            output = gen_calib(color_temps, rgb, yuv)

    if (os.path.exists(directory) == False):
        print('Creating directory:  %s\n' %directory)
        try:
            os.makedirs(directory)
        except OSError as err:
            utils.error('%s: %s' %(err.strerror, err.filename), skip=True)

    filename = os.path.join(directory, '%s_%s.xml' %(params['SENSOR_NAME'], filebase));
    print('Creating XML File:  %s\n' %filename)
    
    module_params = {}
    module_params['NAME']   = 'AWB_DCC_xml'
    module_params['STRUCT_NAME'] = 'awb_alg_dcc_tuning'
    module_params['DCC_ID'] = dcc.DCC_ID_AAA_ALG_AWB_TI3
    module_params['FUNC_GENPARAMS'] = GenAWBParams
    bayer_phase = params['COLOR_PATTERN']
    if bayer_phase > 3:   # not supported
        bayer_phase = 0

    handle = dccxml.OpenFile(filename)
    dccxml.GenHeader(handle, params, module_params)

    handle.write('  <!--=======================================================================-->\n')
    handle.write('     <typedef>\n')
    handle.write('\n')
    handle.write('       <dcc_awb_ref_gray_data_t type="struct">\n')
    handle.write('          <num_of_ref_1   type="uint8"> </num_of_ref_1>\n')
    handle.write('          <num_of_ref_2   type="uint8"> </num_of_ref_2>\n')
    handle.write('          <num_of_gray    type="uint8"> </num_of_gray>\n')
    handle.write('          <radius         type="uint16"> </radius>\n')
    handle.write('          <color_temp_1   type="uint16[]"> </color_temp_1>\n')
    handle.write('          <wbReferenceCb  type="int16[][4]"> </wbReferenceCb>\n')
    handle.write('          <wbReferenceCr  type="int16[][4]"> </wbReferenceCr>\n')
    handle.write('          <ref_gray_R_1   type="uint16[][4]"> </ref_gray_R_1>\n')
    handle.write('          <ref_gray_G_1   type="uint16[][4]"> </ref_gray_G_1>\n')
    handle.write('          <ref_gray_B_1   type="uint16[][4]"> </ref_gray_B_1>\n')
    handle.write('          <ref_index_2    type="uint8[]"> </ref_index_2>\n')
    handle.write('          <color_temp_2   type="uint16[]"> </color_temp_2>\n')
    handle.write('          <referencesCb_2 type="int16[][4]"> </referencesCb_2>\n')
    handle.write('          <referencesCr_2 type="int16[][4]"> </referencesCr_2>\n')
    handle.write('          <ref_gray_R_2   type="uint16[][4]"> </ref_gray_R_2>\n')
    handle.write('          <ref_gray_G_2   type="uint16[][4]"> </ref_gray_G_2>\n')
    handle.write('          <ref_gray_B_2   type="uint16[][4]"> </ref_gray_B_2>\n')
    handle.write('        </dcc_awb_ref_gray_data_t>\n')
    handle.write('\n')
    handle.write('        <dcc_awb_calc_data_t type="struct">\n')
    handle.write('            <awb_basic_ref                type="dcc_awb_ref_gray_data_t">  </awb_basic_ref>\n')
    handle.write('          <img_ref                    type="uint16[]">         </img_ref>\n')
    handle.write('            <luma_awb_min             type="int32">               </luma_awb_min>\n')
    handle.write('            <luma_awb_max             type="int32">               </luma_awb_max>\n')
    handle.write('          <low_color_temp_thresh      type="uint16">              </low_color_temp_thresh>\n')
    handle.write('            <apply_rgb_adjust         type="uint8">               </apply_rgb_adjust>\n')
    handle.write('            <R_adjust                 type="int16">               </R_adjust>\n')
    handle.write('            <B_adjust                 type="int16">               </B_adjust>\n')
    handle.write('            <SB_1                     type="uint16">              </SB_1>\n')
    handle.write('            <SB_2                     type="uint16">              </SB_2>\n')
    handle.write('            <SB_low_bound             type="uint16">              </SB_low_bound>\n')
    handle.write('            <default_T_H              type="uint16">              </default_T_H>\n')
    handle.write('            <default_T_MH               type="uint16">                </default_T_MH>\n')
    handle.write('            <default_T_ML               type="uint16">                </default_T_ML>\n')
    handle.write('            <default_T_L                type="uint16">                </default_T_L>\n')
    handle.write('            <default_T_H_index          type="uint8">             </default_T_H_index>\n')
    handle.write('            <default_T_MH_index         type="uint8">             </default_T_MH_index>\n')
    handle.write('            <default_T_ML_index         type="uint8">             </default_T_ML_index>\n')
    handle.write('            <default_T_L_index            type="uint8">               </default_T_L_index>\n')
    handle.write('            <best_gray_index_default    type="uint8">             </best_gray_index_default>\n')
    handle.write('            <flash_ref                    type="dcc_awb_ref_gray_data_t[4]">   </flash_ref>\n')
    handle.write('          <skin_img_ref               type="uint16[]">         </skin_img_ref>\n')
    handle.write('      </dcc_awb_calc_data_t>\n')
    handle.write('\n')
    handle.write('        <dcc_ti2_color_gain_scalers_t type="struct">\n')
    handle.write('            <dgain  type="uint16">  </dgain>\n')
    handle.write('            <gainGr type="uint16">  </gainGr>\n')
    handle.write('            <gainR  type="uint16">  </gainR>\n')
    handle.write('            <gainGb type="uint16">  </gainGb>\n')
    handle.write('            <gainB  type="uint16">  </gainB>\n')
    handle.write('        </dcc_ti2_color_gain_scalers_t>\n')
    handle.write('\n')
    handle.write('        <dcc_awb_ti2_data_t type="struct">\n')
    handle.write('            <wbModeData type="dcc_ti2_color_gain_scalers_t[]">      </wbModeData>\n')
    handle.write('        </dcc_awb_ti2_data_t>\n')
    handle.write('\n')
    handle.write('        <dcc_awb_supp2_alg3_t       type="struct">\n')
    handle.write('            <use_calib              type="uint16">              </use_calib>\n')
    handle.write('          <blue_index             type="uint16">              </blue_index>\n')
    handle.write('            <red_index              type="uint16">              </red_index>\n')
    handle.write('            <green1_index           type="uint16">              </green1_index>\n')
    handle.write('            <green2_index           type="uint16">              </green2_index>\n')
    handle.write('            <enable_opt             type="uint8">               </enable_opt>\n')
    handle.write('            <max_Cr                 type="int16">               </max_Cr>\n')
    handle.write('            <max_Cb                 type="int16">               </max_Cb>\n')
    handle.write('            <awb_speed              type="uint16">               </awb_speed>\n')    
    handle.write('            <awb_calc_data          type="dcc_awb_calc_data_t">     </awb_calc_data>\n')
    handle.write('            <awb_data               type="dcc_awb_ti2_data_t">      </awb_data>\n')
    handle.write('        </dcc_awb_supp2_alg3_t>\n')
    handle.write('\n')
    handle.write('    </typedef>\n')
    handle.write('  <!--=======================================================================-->\n')

    if(bayer_phase==0):
        red_index = 0
        green1_index = 1
        green2_index = 2
        blue_index = 3
    elif(bayer_phase==1):
        green1_index = 0
        red_index = 1
        blue_index = 2
        green2_index = 3
    elif(bayer_phase==2):
        green2_index = 0
        blue_index = 1
        red_index = 2
        green1_index = 3
    elif(bayer_phase==3):
        blue_index = 0
        green2_index = 1
        green1_index = 2
        red_index = 3
    else:
        print('Warning: unsupported color pattern for AWB (default to RGGB) \n')
        red_index = 0
        green1_index = 1
        green2_index = 2
        blue_index = 3

    handle.write('  <!--=======================================================================-->\n')
    handle.write('    <system_parameters>\n')
    handle.write('      <awb_alg_dcc_tuning type="dcc_awb_supp2_alg3_t" main="general">\n')
    handle.write('\n')
    handle.write(' {\n')
    handle.write('  1,                                   /*use_calib*/\n')
    handle.write('    %d,                                   /*blue_index*/\n' %blue_index)
    handle.write('    %d,                                   /*red_index */\n' %red_index)
    handle.write('    %d,                                   /* green1_index*/\n' %green1_index)
    handle.write('    %d,                                   /* green2_index*/\n' %green2_index)
    handle.write('    1,                                   /* opt_data */\n')
    handle.write('    200,                                   /* max_cr */\n')
    handle.write('    200,                                   /* max_cb */\n')
    handle.write('    6,                                   /* awb_speed */\n')
    handle.write('\n')
    handle.write('      {                           /* ti2_default_awb_calc_data */\n')
    handle.write('      { //awb_ref\n')
    if output:
        handle.write('          {},     // num_of_ref_1\n'.format(output['num_of_ref_1']))
        handle.write('          {},     // num_of_ref_2\n'.format(output['num_of_ref_2']))
        handle.write('          {},     // num_of_gray\n'.format(output['num_of_gray']))
    else:
        handle.write('          1,      // num_of_ref_1\n')
        handle.write('          1,      // num_of_ref_2\n')
        handle.write('          1,      // num_of_gray\n')

    handle.write('          50,     // radius\n')
    handle.write('\n')
    handle.write('       // color_temp_1[num_of_ref_1]\n')
    if output:
        handle.write('         {{ {} }},\n'.format(','.join(str(x) for x in output['colortemp_1'])))
    else:
        handle.write('         {3800},\n')
    handle.write('\n')
    handle.write('       // wbReferenceCb[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    if output:
        for row in output['Cb_1']: handle.write('       {{ {} }},\n'.format(','.join(str(x) for x in row)))
    else:
        handle.write('       {0,0,0,0,},\n')
        
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // wbReferenceCr[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    if output:
        for row in output['Cr_1']: handle.write('       {{ {} }},\n'.format(','.join(str(x) for x in row)))
    else:
        handle.write('       {0,0,0,0,},\n')
    handle.write('\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_R_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    if output:
        for row in output['R_1']: handle.write('       {{ {} }},\n'.format(','.join(str(x) for x in row)))
    else:
        handle.write('       {0,0,0,0,},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_G_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    if output:
        for row in output['G_1']: handle.write('       {{ {} }},\n'.format(','.join(str(x) for x in row)))
    else:
        handle.write('       {0,0,0,0,},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_B_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    if output:
        for row in output['B_1']: handle.write('       {{ {} }},\n'.format(','.join(str(x) for x in row)))
    else:
        handle.write('       {0,0,0,0,},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_index_2[num_of_ref_2]\n')
    if output:
        handle.write('       {{ {} }},\n'.format(','.join(str(x) for x in output['ref_index_2'])))
    else:
        handle.write('       {0},\n')
    handle.write('\n')
    handle.write('   // color_temp_2[num_of_ref_2]\n')
    if output:
        handle.write('       {{ {} }},\n'.format(','.join(str(x) for x in output['colortemp_2'])))
    else:
        handle.write('       {3800},\n')
    handle.write('\n')
    handle.write('   // referencesCb_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    if output:
        for row in output['Cb_2']: handle.write('       {{ {} }},\n'.format(','.join(str(x) for x in row)))
    else:
        handle.write('       {0,0,0,0,},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // referencesCr_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    if output:
        for row in output['Cr_2']: handle.write('       {{ {} }},\n'.format(','.join(str(x) for x in row)))
    else:
        handle.write('       {0,0,0,0,},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_R_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    if output:
        for row in output['R_2']: handle.write('       {{ {} }},\n'.format(','.join(str(x) for x in row)))
    else:
        handle.write('       {0,0,0,0,},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_G_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    if output:
        for row in output['G_2']: handle.write('       {{ {} }},\n'.format(','.join(str(x) for x in row)))
    else:
        handle.write('       {0,0,0,0,},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_B_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    if output:
        for row in output['B_2']: handle.write('       {{ {} }},\n'.format(','.join(str(x) for x in row)))
    else:
        handle.write('       {0,0,0,0,},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('  },\n')
    handle.write('   // img_ref[NUM_OF_REF_2*1120]\n')
    handle.write('   {\n')

    n2 = output['num_of_ref_2'] if output else 1

    for _ in range(35 * n2):
        handle.write('  0,0,0,0,\n')
        handle.write('  0,0,0,0,\n')
        handle.write('  0,0,0,0,\n')
        handle.write('  0,0,0,0,\n')
        handle.write('  0,0,0,0,\n')
        handle.write('  0,0,0,0,\n')
        handle.write('  0,0,0,0,\n')
        handle.write('  0,0,0,0,\n')
        handle.write('\n')

    handle.write('   },\n')
    handle.write('\n')
    handle.write('      // AWB tuning parameters\n')
    handle.write('     20,  // luma_awb_min\n')
    handle.write('  60000,  // luma_awb_max\n')
    handle.write('\n')
    handle.write('      3000,   // low_color_temp_thresh\n')

    if params['WDR_MODE'] == 'wdr':
        handle.write('    100,  // apply_rgb_adjust\n')
        handle.write('      {}, // R_adjust()\n'.format(params['GAMMA_PRE']))
        handle.write('    100,  // B_adjust()\n')
    else:
        handle.write('      0,  // apply_rgb_adjust\n')
        handle.write('      0,  // R_adjust()\n')
        handle.write('      0,  // B_adjust()\n')

    handle.write('\n')
    handle.write('      45, // SB_1\n')
    handle.write('      55, // SB_2\n')
    handle.write('      0,      // SB_low_bound\n')
    handle.write('\n')

    if output:
        x = np.sort(output['colortemp_2'])
        idx = output['ref_index_2']
        handle.write('      {},     // default_T_Hh\n'.format(x[-1]))
        handle.write('      {},     // default_T_MH\n'.format(x[-2]))
        handle.write('      {},     // default_T_ML\n'.format(x[1]))
        handle.write('      {},     // default_T_L\n'.format(x[0]))
        handle.write('\n')
        handle.write('      {},     // default_T_Hh_index\n'.format(idx[-1]))
        handle.write('      {},     // default_T_MH_index\n'.format(idx[-2]))
        handle.write('      {},     // default_T_ML_index\n'.format(idx[1]))
        handle.write('      {},     // default_T_L_index\n'.format(idx[0]))
        handle.write('\n')
    else:
        handle.write('      3800,     // default_T_Hh\n')
        handle.write('      3800,     // default_T_MH\n')
        handle.write('      3800,     // default_T_ML\n')
        handle.write('      3800,     // default_T_L\n')
        handle.write('\n')
        handle.write('      0,      // default_T_Hh_index\n')
        handle.write('      0,      // default_T_MH_index\n')
        handle.write('      0,      // default_T_ML_index\n')
        handle.write('      0,      // default_T_L_index\n')
        handle.write('\n')

    handle.write('      1,     // best_gray_index_default\n')
    handle.write('\n')
    handle.write('\n')
    handle.write('      { //started tuning for flash\n')
    handle.write('          { //flash[0]\n')
    handle.write('          1,          // num_of_ref_1\n')
    handle.write('          1,          // num_of_ref_2\n')
    handle.write('          1,      // num_of_gray\n')
    handle.write('          50,     // radius\n')
    handle.write('\n')
    handle.write('       // color_temp_1[num_of_ref_1]\n')
    handle.write('         {3800},\n')
    handle.write('\n')
    handle.write('             // wbReferenceCb[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // wbReferenceCr[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_R_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_G_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_B_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_index_2[num_of_ref_2]\n')
    handle.write('   {0},\n')
    handle.write('\n')
    handle.write('   // color_temp_2[num_of_ref_2]\n')
    handle.write('   {3800},\n')
    handle.write('\n')
    handle.write('   // referencesCb_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // referencesCr_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_R_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_G_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_B_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   },\n')
    handle.write('          { //flash[1]\n')
    handle.write('          1,          // num_of_ref_1\n')
    handle.write('          1,          // num_of_ref_2\n')
    handle.write('          1,      // num_of_gray\n')
    handle.write('          50,     // radius\n')
    handle.write('\n')
    handle.write('       // color_temp_1[num_of_ref_1]\n')
    handle.write('         {3800},\n')
    handle.write('\n')
    handle.write('             // wbReferenceCb[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // wbReferenceCr[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_R_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_G_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_B_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_index_2[num_of_ref_2]\n')
    handle.write('   {0},\n')
    handle.write('\n')
    handle.write('   // color_temp_2[num_of_ref_2]\n')
    handle.write('   {3800},\n')
    handle.write('\n')
    handle.write('\n')
    handle.write('   // referencesCb_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // referencesCr_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_R_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_G_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_B_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   },\n')
    handle.write('          { //flash[2]\n')
    handle.write('          1,          // num_of_ref_1\n')
    handle.write('          1,          // num_of_ref_2\n')
    handle.write('          1,      // num_of_gray\n')
    handle.write('          50,     // radius\n')
    handle.write('\n')
    handle.write('       // color_temp_1[num_of_ref_1]\n')
    handle.write('         {3800},\n')
    handle.write('\n')
    handle.write('             // wbReferenceCb[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // wbReferenceCr[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_R_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_G_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_B_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_index_2[num_of_ref_2]\n')
    handle.write('   {0},\n')
    handle.write('\n')
    handle.write('   // color_temp_2[num_of_ref_2]\n')
    handle.write('   {3800},\n')
    handle.write('\n')
    handle.write('   // referencesCb_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // referencesCr_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_R_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_G_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_B_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   },\n')
    handle.write('          { //flash[3]\n')
    handle.write('          1,          // num_of_ref_1\n')
    handle.write('          1,          // num_of_ref_2\n')
    handle.write('          1,      // num_of_gray\n')
    handle.write('          50,     // radius\n')
    handle.write('\n')
    handle.write('       // color_temp_1[num_of_ref_1]\n')
    handle.write('         {3800},\n')
    handle.write('\n')
    handle.write('             // wbReferenceCb[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // wbReferenceCr[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_R_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_G_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_B_1[num_of_ref_1][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_index_2[num_of_ref_2]\n')
    handle.write('   {0},\n')
    handle.write('\n')
    handle.write('   // color_temp_2[num_of_ref_2]\n')
    handle.write('   {3800},\n')
    handle.write('\n')
    handle.write('   // referencesCb_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // referencesCr_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_R_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_G_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   // ref_gray_B_2[num_of_ref_2][num_of_gray]\n')
    handle.write('   {\n')
    handle.write('       {0,0,0,0},\n')
    handle.write('   },\n')
    handle.write('\n')
    handle.write('   },\n')
    handle.write('      },//end of tuning data for flsh\n')
    handle.write('      {\n')
    handle.write('\n')
    handle.write('// skin histogram:\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('0, 0, 0, 0,\n')
    handle.write('\n')
    handle.write('      },//end of skin histogram data\n')
    handle.write('\n')
    handle.write('  }, //end of awb_calc_data\n')
    handle.write('\n')
    handle.write('\n')
    handle.write('  {\n')
    handle.write('      //User modes dcc_ti2_color_gain_scalers_t[]\n')
    handle.write('NULL,\n')
    handle.write('  },\n')
    handle.write('}\n')
    handle.write('     </awb_alg_dcc_tuning>\n')
    handle.write('  </system_parameters>\n')
    handle.write('\n')
    handle.write('  <!--=====================================================================-->\n')
    
    dccxml.GenFooter(handle, module_params)
    dccxml.CloseFile(handle)
